### ISSUE TITLE
Publishing on conan

### ISSUE THREAD

**Issue by bendardenne** [Kistler-Group/sdbus-cpp#100]
Hi,

First of all, thanks for this nifty lib. Very easy to use. 

I'm currently using it for a [pet project](https://github.com/bendardenne/medor) of mine. I use conan for resolving dependencies. 

I found a conanfile for sdbus-cpp [here](https://github.com/cyllene-project/conan-sdbus-cpp). It's a bit outdated, so I fixed it ([here](https://gist.github.com/bendardenne/0469bd170a27d764567a76706c752a57)). I then publish this on a repository I created on bintray.

I was wondering if you would be interested in integrating this in the project.  

I feel like other people could benefit from this, and I think it would be best if someone actively involved in the project had ownership of the artifact and repository.

That being said, if you don't wish to do this, I'm okay with keeping my conanfile and maintaining my own artifact on bintray for my project.

If you were to set up some CI as mentioned #44, you could probably automate the publication of tagged versions, too.

**Comment by sangelovic** [comment]
Hi,

thanks a lot for reaching out, and sorry for out-of-date reply, this is now a hobby project for me and am now often busy with other things.

Providing a Conan sdbus-c++ recipe/package seems a reasonable thing. But I'm not familiar with Conan :) Could you elaborate more on what do you mean by integrating Conan into the project?

I understand from your message that there are two ways of publishing a Conan recipe: bintray (or something external for that matter), and a recipe shipped with/integrated directly into the library project. The latter seems reasonable (the recipe lays where the build description and the sources are), and if it's a modern best practice for projects publishing on Conan, so I'm definitely open to explore that opportunity.

I'd be happy if you could give more info (maybe some links). Potentially even submit a merge request where we could discuss more.
