### ISSUE TITLE
sdbus-c++-xml2cpp generates invalid code

### ISSUE THREAD

**Issue by ChristianS99** [Kistler-Group/sdbus-cpp#101]
when parameters of methods/signals are named after c++ keywords (e.g. "new") xml2cpp just uses this, which results in invalid c++ code. Example "from the wild":
https://www.freedesktop.org/software/ModemManager/api/latest/gdbus-org.freedesktop.ModemManager1.Modem.html#gdbus-signal-org-freedesktop-ModemManager1-Modem.StateChanged
https://cgit.freedesktop.org/ModemManager/ModemManager/tree/introspection/org.freedesktop.ModemManager1.Modem.xml?id=6c37488d4ebbbb2afdefce193e6fb4070cde8ab3

Proposal: add _ at the end of names that equal reserved keywords in c++ (https://en.cppreference.com/w/cpp/keyword). Eg: new -> new_

I would give this a try myself, just wanted to ask, if this is fine for you or if you have different ideas, how to handle this.

**Comment by sangelovic** [comment]
Hi, I agree with your suggestion. Feel free to implement that and post a
pull request. Thanks a lot!

**Comment by ChristianS99** [comment]
OK, great. Will go for it.
Does anyone have ideas, if there are more problematic names beside the c++ keywords?

**Comment by sangelovic** [comment]
AFAIK, C++ keywords (https://en.cppreference.com/w/cpp/keyword, the first
table on the page) are the only reserved words that cannot be used as names
of variables etc. They also cover C keywords. So this should be the
definitive list, which covers C++ up to C++20.

**Comment by ChristianS99** [comment]
What about common defines like NULL?
using NULL as a name is strictly allowed, but I would bet there are hardly any programs in the world, where this doesn't lead to problems?
Should those be handled, too?

**Comment by sangelovic** [comment]
Good point. In my view, if we take into account common defines too, the
question is where do we stop? We make it safe for most common defines, or
also moderately common defines, or also for less common (but still common)
defines? And who would define what is more important?

We need to draw the line somewhere. That said, maybe it could be the c++
keywords + NULL, since NULL is (was) so ubiquitous.

Additionally, how many interfaces will have a parameter/function/signal
named NULL?

I don't have a clear opinion, but I somehow feel we don't have to make a
science out of it.

**Comment by ChristianS99** [comment]
Created PR for c++keywords and NULL.

It's hard to draw a line somewhere, but for the beginning, I think this is OK with those, the list can be easily expanded as need arises.

Something even more academic:
if you have an interface with a method, that has two parameters "new" and "new_".
Now, this would create a c++ class that has two parameters named "new_" and "new_", what is invalid.
No question, designing Interfaces like that is pathetic, but it's valid DBus AFAIK.
Don't think, it's worth to fix this, but thought, I should mention it.

**Comment by sangelovic** [comment]
In such corner cases, the one still has three choices:

* either they will stop using the generated sdbus-c++ stubs and will use slightly lower-level, but still very convenient library API,
* or they will themselves modify (post-process) the generated stub headers of theirs to fix the problematic names,
* or if they see the generic pattern on how to solve this for others, they could contribute, like you now :o)

So I agree to stick to the list of keywords that we have now.
