### ISSUE TITLE
Compatibility with systemd 245.6

### ISSUE THREAD

**Issue by peckato1** [Kistler-Group/sdbus-cpp#106]
Hello,

I'm unable to use sdbus-c++ 0.8.1 with the new systemd 245.6. When I compile and run the following simple program querying systemd's state on my ArchLinux machine with `systemd-libs==245.6-2` (this package provides libsystemd), this is what I get:

```cpp
#include <iostream>
#include <sdbus-c++/sdbus-c++.h>

int main ( ) {
    auto conn = sdbus::createSystemBusConnection();
    auto proxy = sdbus::createProxy(*conn, "org.freedesktop.systemd1", "/org/freedesktop/systemd1");
    std::cout << "Value: " << (std::string) proxy->getProperty("SystemState").onInterface("org.freedesktop.systemd1.Manager") << std::endl;
}
```

```
terminate called after throwing an instance of 'sdbus::Error'
  what():  [org.freedesktop.DBus.Error.InvalidArgs] Failed to create a plain message (Invalid argument)
```

However, on my (not-yet updated) other machine with `systemd-libs==245.5-2` this works as expected:
```
Value: running
```

When I downgrade the first machine's systemd to `245.5-2`, it works as expected.

sdbus-c++ was compiled using [this PKGBUILD from AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sdbus-cpp).

**Comment by martin-koch** [comment]
I just came across the same issue. It seems like [this] (https://github.com/systemd/systemd/commit/a2dd991d0fde59dc0574bd4d0c1438f01dc0b8ff) systemd commit causes the problem.

**Comment by sangelovic** [comment]
A bug was filed at systemd: https://github.com/systemd/systemd/issues/16193

**Comment by sangelovic** [comment]
The bug was fixed by systemd via https://github.com/systemd/systemd/pull/16237. I think we can close this issue.
