### ISSUE TITLE
Query bus for given service

### ISSUE THREAD

**Issue by tomasz-grobelny** [Kistler-Group/sdbus-cpp#111]
How do I query DBus for a specific service? Suppose I have open connection (created using eg. `sdbus::createSessionBusConnection`) and I want to implement this function:

```
bool has_service_with_name(const std::string &name) {
  auto r = sd_bus_get_name_creds(bus_,
                                 name.c_str(),
                                 0,
                                 nullptr);
  return r >= 0;
}

```

Currently I do not see a way to get `sd_bus*` from `IConnection`. Shouldn't there be a way to get it? Or another way - should there be a way to construct `Connection` from `sd_bus*`? Would a patch implementing either solution be accepted?

**Comment by sangelovic** [comment]
The best way would be to implement a wrapper with a sensible name for this `sd_bus` function directly under `Connection` class in the library, and provide a public API virtual function in `IConnection`. Such a solution should be accepted.

**Comment by sangelovic** [comment]
One of design tenets of sdbus-c++ is to provide an API on a higher level of abstraction which is completely independent of sd-bus. sd-bus does not leak all the way up to sdbus-c++ API, and is hidden inside. Hence, there is no way to get sd-bus constructs from sdbus-c++ abstractions.
