### ISSUE TITLE
Problems receiving D-Bus dictionary with method

### ISSUE THREAD

**Issue by tlammi** [Kistler-Group/sdbus-cpp#116]
I'm implementing a Bluetooth GATT server using BlueZ and I'm having issues with receiving a D-Bus dictionary with ReadValue-method.

*System*: Linux 5.7.9-1 MANJARO
*sdbus-cpp*: 0.8.1 and 0.8.2
*dbus-monitor output*:
```
method call time=1597215239.378169 sender=:1.2 -> destination=:1.1818 serial=20046 path=/org/something/service0/char0; interface=org.bluez.GattCharacteristic1; member=ReadValue
   array [
      dict entry(
         string "device"
         variant             object path "/org/bluez/hci0/dev_AC_57_75_0A_AB_EB"
      )
      dict entry(
         string "link"
         variant             string "LE"
      )
      dict entry(
         string "mtu"
         variant             uint16 517
      )
   ]
...
error time=1597215239.380343 sender=:1.1818 -> destination=:1.2 error_name=org.freedesktop.DBus.Error.InvalidArgs reply_serial=20046
   string "Failed to create a plain message (Invalid argument)"
```
Method registration:
```C++
using Dict = std::map<std::string, sdbus::Variant>;
obj_->registerMethod("ReadValue")
    .onInterface(GATT_CHARAC_IFACE)
    .implementedAs([&](const Dict& opts) -> std::vector<uint8_t> {
      std::cerr << "ReadValue called\n";
      return rhandler_(opts);
    });
```
Method prototype: `array{byte} ReadValue(dict options)`, spec can be found in: https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt#n62

**Comment by tlammi** [comment]
After debugging with GDB, it seems that the issue is this: https://github.com/systemd/systemd/issues/16193
sdbus-cpp seems to fail in constructing an empty variant before calling the callback:
https://github.com/Kistler-Group/sdbus-cpp/blob/v0.8.2/include/sdbus-c++/Message.h#L350

**Comment by sangelovic** [comment]
The systemd issue you referenced explains it all. Please wait and upgrade to newer systemd or compile sdbus-c++ with embedded libsystemd (in which case you can choose a version of systemd which does not exhibit that undesired breaking behavior).

**Comment by tlammi** [comment]
The issue disappeared with system upgrade.
