### ISSUE TITLE
std::map <uint8_t, sdbus::Variant v(std::vector<uint8_t> >> turns into a{yay}, while expected a{yv}

### ISSUE THREAD

**Issue by snilga-gl** [Kistler-Group/sdbus-cpp#119]
Hello!

I' am trying to use sdbus-c++ to control BLE advertisement using BlueZ. One of D-Bus properties which I shall register for BlueZ has signature a{yv}, which is a dictionary where keys are D-Bus 'bytes' and values are 'D-Bus variant'. 
However when I create  std::map <uint8_t, sdbus::Variant v(std::vector<uint8_t> >> to represent data format accepted by BlueZ, I see that in turns into a{yay}, so BlueZ tells me it cannot parse my data.
Please advice.

**Comment by sangelovic** [comment]
Hello!

`std::map <uint8_t, sdbus::Variant v(std::vector<uint8_t> >>` is not a valid construct in C++, so that cannot be the type you're using. What exactly are you trying to do? Perhaps you can paste code fragment?

As you say, `a{yv}` signature turns into `std::map<uint8_t, sdbus::Variant>` type representation in C++. And `a{yay}` would turn into `std::map<uint8_t, std::vector<uint8_t>>` type in C++. There are [unit tests](https://github.com/Kistler-Group/sdbus-cpp/blob/master/tests/unittests/TypeTraits_test.cpp#L100) for such use cases. Maybe in the first step make sure you don't have a typo on your part.

**Comment by snilga-gl** [comment]
Here is a code sample 

```
	object_->registerProperty("org.bluez.LEAdvertisement1", "Data", "a{yv}", [](sdbus::PropertyGetReply& reply) {

		spdlog::trace("advetiser->getData");

		std::vector <uint8_t> data = {1, 2, 3, 4, 5, 6};
		std::map <uint8_t, sdbus::Variant> v;
	        v.insert(std::make_pair(0xFF, sdbus::Variant(data)));

		reply << v;
	});
```
I might have been compiled the library using some old compiler. Will run the tests to see if they passed

**Comment by snilga-gl** [comment]
BTW there is indeed a unit test verifying that type sdbus::Variant turns into 'v'. Is there any API which I could I call to log the reply and make sure that when sdbus::Variant is initialized using std::vector<uint8> in the code below, the whole reply will be be 'a{yv}', and not  `a{yay}' ?
Thank you in advance !

**Comment by sangelovic** [comment]
If there was a mismatch of types, sd-bus would catch it early in message marshalling. But you say it's the client that's unhappy.

From what I read at https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/advertising-api.txt, to me it seems the Data property is of type `a{yay}`, not `a{yv}`.

So I guess this is what you need (written using more convenient API where you don't have to deal with signatures and stuff):

```c++
object_->registerProperty("Data").onInterface("org.bluez.LEAdvertisement1").withGetter([this](){
    spdlog::trace("advetiser->getData");
    std::vector<uint8_t> data = {1, 2, 3, 4, 5, 6};
    std::map<uint8_t, std::vector<uint8_t>> v;
    v.insert(std::make_pair(0xFF, data));
    return v;
});
```

which could btw be completely simplified to:

```c++
object_->registerProperty("Data").onInterface("org.bluez.LEAdvertisement1").withGetter([this](){
    spdlog::trace("advetiser->getData");
    return std::map<uint8_t, std::vector<uint8_t>>{{0xFF, {1, 2, 3, 4, 5, 6}}};
});
```

sdbus-c++ will infer all what it needs from your high-level code here. You don't have to use more cumbersome lower-level ways of doing that.

**Comment by sangelovic** [comment]
Have you solved your issue?

**Comment by snilga-gl** [comment]
@sangelovic, yes, the issue was actually related to BlueZ: it did not accept my call because  the adapter did not support the feature I was trying to enable. Sorry for bothering !
