### ISSUE TITLE
Reply messages are written to d-bus with (potentially very long) delay

### ISSUE THREAD

**Issue by m-blaha** [Kistler-Group/sdbus-cpp#126]
Hi,

I'm struggling with problem when reply messages are written to d-bus with a delay (sometimes really long one like tens or even hundreds of seconds).

Let say I have a dbus method registered like this:

```
dbus_object->registerMethod(
        THE_INTERFACE, "list", "a{sv}", "aa{sv}", [this](sdbus::MethodCall call) -> void {
            this->list(std::move(call));
        });
connection->enterEventLoop();
```

the handler runs asynchronously and the processing of the request can take longer time:

```
void list(sdbus::MethodCall && call) {
    auto worker = std::thread([](sdbus::MethodCall call) {
        // here are the data prepared
     
        auto reply = call.createReply();
        reply << output_list;
        reply.send();
    })
}
```

The `output_list` could be possibly quite big (like tens of MB) and the larger the `output_list` is the bigger is the probability that reply is not actually written to the d-bus (in fact it eventually is, but the delay could be really long).

The problem is following

- the main event loop in `Connection::enterEventLoop()` polls the client request for `list()` method call, processes it (this is fast because it is asynchronous) and waits for the next request.

- the `list()` method prepares the data and calls `reply.send()` which succeeds.

But in the underlying systemd code are two possible results of sending the message (see https://github.com/systemd/systemd/blob/d625e59d0745649f3c8c9fd37439c24a80ff2a82/src/libsystemd/sd-bus/sd-bus.c#L1953):

- the whole message was written - then everything is OK and the client is going to get his results

- only part of the message was written - the message is put in the queue and will be send during the next `sd_bus_process()` call. And here is the problem - the `sd_bus_process()` is not called again until the main event loop polls the next request (which could take a long time) or the `poll()` time-outs.

I tried to dirty patch `Connection::waitForNextRequest()` method and set `timeout` to 100ms instead of the default `UINT64_MAX` and of course this worked (and according to `sd_bus_get_timeout()` documentation "It is permissible (and even expected) that shorter time-outs are used by the calling program").

So one solution could be making the `timeout` somehow configurable and instead of directly using `sd_bus_get_timeout()` output pass to `poll()` something like `min(sd_bus_get_timeout(), configured_timeout)`.

Do you see any other solutions? Thanks for any help.

**Comment by sangelovic** [comment]
Hi. Thanks for reporting and for detailed, comprehensive pre-analysis.
That's what I appreciate a lot (and it's so rare at the same time). I don't
have time now, but I'll come back to this soon.
