### ISSUE TITLE
Tutorial doesnt show how to control to which bus a proxy object will connect

### ISSUE THREAD

**Issue by Oberonc** [Kistler-Group/sdbus-cpp#13]
The tutorial doesnt show how to control to which bus a proxy object will connect (system bus or session bus).

**Comment by sangelovic** [comment]
In the client code example in the tutorial, there was a comment at the proxy creation and the paragraph below it explaining shortly that stuff. But I understood now it might not have been clear enough, so I rephrased the comment to

```c++
    // Create proxy object for the concatenator object on the server side. Since here
    // we are creating the proxy instance without passing connection to it, the proxy
    // will create its own connection automatically, and it will be system bus connection.
```

and the paragraph underneath:

The object proxy can be created by either explicitly passing the connection object to it, or without the connection object. In the former case, we have the freedom of creating our own connection (to either system bus or to session bus) and then we can just move that connection object as the first argument of the proxy factory. The latter option is more convenient (no messing with connection for proxy), the proxy will create and manage its own connection, but the limitation is that it will be the connection to the system bus only.

Is that okay for you?

**Comment by CarloWood** [comment]
Happy to have found this, because that info seems to (still) be missing from the tutorial.
I failed to connect as stated above after setting up the server on the session bus with:

    const char* serviceName = "org.sdbuscpp.concatenator";
    auto connection         = sdbus::createSessionBusConnection(serviceName);

After reading the above I tried the following on the client:

    const char* serviceName = "org.sdbuscpp.concatenator";
    auto connection         = sdbus::createSessionBusConnection(serviceName);
    const char* destinationName = "org.sdbuscpp.concatenator";
    const char* objectPath      = "/org/sdbuscpp/concatenator";
    auto concatenatorProxy      = sdbus::createProxy(std::move(connection), destinationName, objectPath);

which fails (at the second line) with:

    terminate called after throwing an instance of 'sdbus::Error'
      what():  [org.freedesktop.DBus.Error.FileExists] Failed to request bus name (File exists)

How am I supposed to do this?
Thanks in advance.

**Comment by CarloWood** [comment]
Ok, I figured it out...

    auto connection = sdbus::createSessionBusConnection();

not passing a name thus. Where can I find this in the documentation?
