### ISSUE TITLE
MemoryLeak in EmitSignal

### ISSUE THREAD

**Issue by ChristianS99** [Kistler-Group/sdbus-cpp#132]
```
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__beacon_adaptor_hpp__adaptor__H__
#define __sdbuscpp__beacon_adaptor_hpp__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>
#include <thread>

namespace test {

class beacon_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "test.beacon";

protected:
    beacon_adaptor(sdbus::IObject& object)
        : object_(object)
    {
        object_.registerSignal("beacon").onInterface(INTERFACE_NAME);
    }

    ~beacon_adaptor() = default;

public:
    void emitBeacon()
    {
        object_.emitSignal("beacon").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IObject& object_;
};

} // namespaces

#endif
class beacon : public sdbus::AdaptorInterfaces<test::beacon_adaptor>
{
public:
    beacon(sdbus::IConnection& connection, std::string objectPath)
        : sdbus::AdaptorInterfaces<test::beacon_adaptor>(connection, std::move(objectPath))
    {
        registerAdaptor();
    }

    ~beacon()
    {
        unregisterAdaptor();
    }

};
int main()
{
    auto connection = sdbus::createSessionBusConnection(beacon::INTERFACE_NAME);
    connection->enterEventLoopAsync();
    const char* objectPath = "/test/beacon";
    beacon b(*connection, objectPath);
    while (true) {
        b.emitBeacon();
        std::this_thread::sleep_for(std::chrono::milliseconds(2));
    }
    connection->leaveEventLoop();
}
```

this programm leaks memory, about 1MB/s. it's proportional to the frequency of the beacons, so when sleeping for 20ms, it's only 100kB/s. 
ASAN isn't complaining, so I would guess, there is some container increasing in size.

**Comment by riuriuriu** [comment]
Thanks @ChristianS99 for the report with a detailed example and sorry for the delay. 

I can't reproduce a leak when running your supplied test code against the current master. I checked it using `valgrind --tool=massif`. What tool or process info did you use to check the heap allocation?

**Comment by ChristianS99** [comment]
Actually, I used no special tool. Just run the code and observe the memory usage.

It's not a memoryleak in the sense that allocated memory is inaccessible, that would be seen by tools, probably.
It's more that it adds items to a collection, at each iteration or something like that. the collection has still access to the memory and cleans up at end of program, so tools are happy.
But if you just add an element to a collection regularly without ever removing, you just use up memory. 
You could argue if this is a "leak", it's probably not always a leak, as there might be valid cases to just add to a collection without removing. But then, the program needs to be prepared to run out of memory.
But in this case, I think it is a leak, because emitting a signal shouldn't store something in memory for longer times (at least, I wouldn't expect that). Maybe the lib handles OOM gracefully, didn't run it that long, as it's also not very fast.

**Comment by ChristianS99** [comment]
hmm, I just tried to reproduce it myself, without success.
I can't remember any more, that i did something else except running the given program. I tried with current head and with rev from the time I opened the issue (d6fdacafbe5e490d540956fe78f8df808723f49e), but both don't seem to leak with the given program.

Sorry for the noise then. feel free to close

**Comment by riuriuriu** [comment]
I didn't only check for leaks but also for just growing memory usage which I wasn't able to reproduce. So I'll close this issue.
