### ISSUE TITLE
Class that inherits from multiple proxies

### ISSUE THREAD

**Issue by Oberonc** [Kistler-Group/sdbus-cpp#14]
The tutorial shows inheritance from a single proxy class (with a comment on where to place more interfaces).
The problem here are:
1. It's not clear to which bus it will connect.
2. Isnt clear if it will share connection between parents (it will).

**Comment by sangelovic** [comment]
Tried to clarify this better in the tutorial. The second point shall be clear anyway, since there is just one proxy even when it represents many interfaces (the parents are just a notion of D-Bus interface), thus one proxy uses one connection.
