### ISSUE TITLE
Use of deleted memory?

### ISSUE THREAD

**Issue by CarloWood** [Kistler-Group/sdbus-cpp#143]
https://github.com/Kistler-Group/sdbus-cpp/blob/d6fdacafbe5e490d540956fe78f8df808723f49e/src/Proxy.cpp#L307

This line could delete the connection, but the next line it is used.
Seems like a bug to me?

**Comment by dleeds-cpi** [comment]
See https://en.cppreference.com/w/cpp/memory/unique_ptr/release. `release()` gives up ownership of the pointer, but does not call the deleter like `reset()`.

**Comment by CarloWood** [comment]
Yeah sorry, I found that later but forgot to close this issue.
