### ISSUE TITLE
Server with Async methods hogs the CPU

### ISSUE THREAD

**Issue by Oberonc** [Kistler-Group/sdbus-cpp#15]
When you create a server with async methods and run it and then call one of the async methods the processing loop will start hogging the CPU.
Can be seen in "top" and using gprof or callgrind (to pinpoint the locations).

**Comment by lukasdurfina** [comment]
Hi Oberonc,
thank you for the report. I will try to take a look on it soon.

**Comment by Oberonc** [comment]
After some investigation I can tell that when a server has at least one async method and that method is called "waitForNextRequest()" will not block anymore.

**Comment by lukasdurfina** [comment]
Thanks to @sangelovic, it's fixed in v0.3.1
