### ISSUE TITLE
can't use std::bind for `implementedAs`

### ISSUE THREAD

**Issue by hellow554** [Kistler-Group/sdbus-cpp#152]
Let's image this code:

```
struct Context {};
auto ctx = Context{};
auto connection = sdbus::createSystemBusConnection(SERVICE_NAME);
ctx.obj         = sdbus::createObject(*connection, OBJECT_PATH);

ctx.obj->registerMethod(METHOD_SETENTITY)
    .onInterface(INTERFACE_NAME)
    .withNoReply()
    .implementedAs([&ctx](const std::string &a, const std::string &b) { myFunc(ctx, a, b); });
//    .implementedAs(std::bind(&myFunc, ctx, std::placeholders::_1, std::placeholders::_2));
```

the two `implementedAs` are programacitally identical, expcept that the latter does not compile. I think it's cleaner and simple than providing a lambda and I certainly don't want to expose `ctx` as a global variable.

**Comment by sangelovic** [comment]
Lambdas are generally preferred to `std::bind` in modern C++, for several reasons. (Consult Effective Modern C++ book by Scott Meyers, Item 34: "Prefer lambdas to std::bind", or https://abseil.io/tips/108 - there is also a good elaboration here, or https://clang.llvm.org/extra/clang-tidy/checks/modernize-avoid-bind.html, etc...).

The problem with `std::bind` here is that the resulting object is of unspecified type by the standard (i.e. it's compiler-specific implementation), and its `operator()` is templated. I can see the following solutions:

1. On our side -- add support to sdbus-c++ function type traits to recognize it's a functor from `std::bind`. But that would mean compiler-specific handling, `#ifdefs`, and all that unpleasant and additional complicated stuff, just like e.g. here: https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/function_traits.hpp, lines 81 - 127. I don't like that, honestly, given the complexity, given the dependency on specific compiler implementation (which can change at any time) of `std::bind`, and given the general preference of lambdas to `std::bind` in modern C++ world.
2. On your side -- you can explicitly construct `std::function<Context*, const std::string &, const std::string &>` object our of your `std::bind` call. That will work with sdbus-c++ function traits.
3. On your side -- you just switch to lambda, which, in my view, is way more readable than bind :) This approach I'd like the most.

So I propose the fix on your side -- i.e. either 2. or 3. What do you think?

**Comment by sangelovic** [comment]
And you don't have to expose `ctx` as a global variable at all with lambdas.

**Comment by hellow554** [comment]
So I slept over this. I still think, that a bind is much easier to read and maintain then a lambda, but I can follow your arguments.

I think the thing that bothers me most is the reptition of the arguments, e.g. I have to explictly name them in the lambda once and in the function a second time, but that is a C++ problem, not a sdbus one.

I'm not sure how to deal with this, but I see, that you self-assigned this to you.
It's up to you whether you want to spend some more time on this or just close it, I'm fine with both (:

**Comment by sangelovic** [comment]
I understand your point. I would be open towards supporting std::bind, but I don't consider it worthy given the amount of non-standard code with several variants and with checks for specific compiler vendors, including efforts for proper testing and future maintenance. Hence, I'd close this issue, hoping that you can live with lambdas here. Is it OK?

**Comment by hellow554** [comment]
Can you tell me where exactly the lambda is used in your code? Maybe the distinction isn't needed at all? Just give me a small hint where to look at.

**Comment by hellow554** [comment]
The reason I'm asking is if you're only interested in the result, you could use [`std::invoke_result`](https://en.cppreference.com/w/cpp/types/result_of), if you're interested in the argument, that another story...

**Comment by sangelovic** [comment]
You probably mean where the callback signature is introspected? Here, for example: https://github.com/Kistler-Group/sdbus-cpp/blob/master/include/sdbus-c%2B%2B/ConvenienceApiClasses.inl, on line 93, 94, 99.

We need to know exactly the *entire* signature of the callback, i.e. the types of callback input parameters as well as return values. `function_traits` template in `TypeTraits.h` is used for introspection. And we would have to specialize that template for various non-standard, compiler vendor-dependent implementations of `std::bind` result type. Whenever a compiler vendor changes its internal implementation of that, we'd have to add another `#ifdef` for that.
