### ISSUE TITLE
unable to connect to tcp socket

### ISSUE THREAD

**Issue by marcinosypka** [Kistler-Group/sdbus-cpp#154]
I have set the environmental variable 
`DBUS_SYSTEM_BUS_ADDRESS=tcp:host=172.17.0.2,port=55000,family=ipv4`

to connect to the dbus-daemon on different host
but when creating connection with:
`auto conn = sdbus::createSystemBusConnection()`
I'm getting the error:
[System.Error.ENOTCONN] Failed to flush bus on opening (Transport endpoint is not connected)

I can send messages to the address above via dbus-send or python dbus module, but I'm unable to connect to given address with sdbus-cpp lib.

**Comment by sangelovic** [comment]
Could you please try that with pure sd-bus implementation? If that wouldn't work either, please report that to systemd. Otherwise please come back to us. Thanks.
