### ISSUE TITLE
Failed to enter container

### ISSUE THREAD

**Issue by salmanisd** [Kistler-Group/sdbus-cpp#165]
I have a service whose PropertiesChanged signal is described as.
```
  <signal name="PropertiesChanged">
   <arg name="interface_name" type="s"/>
   <arg name="changed_properties" type="a{sv}"/>
   <arg name="invalidated_properties" type="as"/>
  </signal>
```
Correspondingly, sdbus autogens the callback with the following signature.
```
    virtual void onPropertiesChanged(const std::string& interface_name, const std::map<std::string, sdbus::Variant>& changed_properties, const std::vector<std::string>& invalidated_properties) = 0;
``` 
My problem is whenever this callback is triggered and this function is called, I get an error message from sdbus "Failed to enter container" 

I noticed the external service doesnt always serve the ```"invalidated_properties```
e.g) using dbus-monitor
```
signal time=1615963580.368345 sender=:1.29 -> destination=(null destination) serial=740088 path=/org/fedorahosted/certmonger/requests/Request1; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged 
   string "org.fedorahosted.certmonger.request" 
   array [ 
      dict entry( 
         string "status" 
         variant             string "NEED_KEY_PAIR" 
      ) 
   ] 
```
I wrote my own ```onPropertiesChanged``` callback omitting the ``` const std::vector<std::string>& invalidated_properties``` from the signature and now everything works fine.
Seems like sdbus-cpp always expects the third parameter to exist and fails when it doesnt. Is it the expected behaviour? or should it act like dbus-monitor?

**Comment by sangelovic** [comment]
Is the service object providing this signal on standard D-Bus interface `org.freedesktop.DBus.Properties`? If so, according to my knowledge, the `invalidated_properties` argument should be always there. If it's empty, then it's empty, but the argument (an empty `vector` in this case) is there. If it isn't, then I'm not sure, could this be a bug on the service part?

A dbus-monitor output in this [SO question](https://stackoverflow.com/questions/64119289/how-to-properly-connect-the-propertieschanged-signal-of-org-freedesktop-dbus) nicely show empty `invalidated_properties` argument.

`libsystemd` also puts the `invalidated_properties` always into the signal, even if the collection is empty...

**Comment by sangelovic** [comment]
If you can't change service's behavior, then an alternative (less convenient to you, probably) is that you move from generated adaptor/proxy classes down to lower level sdbus-c++ API, based on `Message`s. Then, when extracting away arguments from a message, there are ways to check whether there is still data (i.e., next argument) left in the message. If yes -- you take it out. If not, you stop extracting arguments from the message. This way you could graciously handle messages with "optional arguments".

**Comment by salmanisd** [comment]
Yes this is on ```org.freedesktop.DBus.Properties``` (as shown in the dbus-monitor output above).

I am already using the low level API to workaround this issue and its working without any problems. 
I just thought maybe sdbus-cpp could also handle this case without failing (like dbus-monitor does).

Please feel free to close this issue. Regards

**Comment by sangelovic** [comment]
OK. The difference between `dbus-monitor` and `sdbus-c++`-generated methods is that `dbus-monitor` is generic and process a D-Bus message in a generic way, by peeking what's inside the message and taking it out then, whereas a generated method expects a given number of arguments of given type and sequence inside the message.

`sdbus-c++` could potentially implement support for optional arguments also on this level. But for this specific case, the service itself seems to have a bug, since the D-Bus specs say nothing about the "optionality" of that parameter.

Closing the issue for now.
