### ISSUE TITLE
Getting something useful out of dbus variant types?

### ISSUE THREAD

**Issue by dieggsy** [Kistler-Group/sdbus-cpp#18]
I'm pretty new to C++, but I was trying a simple program to show active NetworkManager connections with sdbus-cpp:

```C++
#include <iostream>
#include <typeinfo>
#include <sdbus-c++/sdbus-c++.h>

int main () {
    const char* destination_name = "org.freedesktop.NetworkManager";
    const char* object_path = "/org/freedesktop/NetworkManager";
    auto nm_proxy = sdbus::createObjectProxy(destination_name, object_path);

    // const char* interface_name = "org.freedesktop.NetworkManager";
    auto cons = nm_proxy->getProperty("ActiveConnections").onInterface("org.freedesktop.NetworkManager");
    auto that = cons.get<std::vector<std::string>>();
    for (const auto elem : that) {
        std::cout << elem << '\n';
    }
    return 0;
}
```
But this fails with:
```
terminate called after throwing an instance of 'sdbus::Error'
  what():  [System.Error.ENXIO] Failed to enter a variant (No such device or address)
aborted (core dumped)
```
Would you happen to know what I'm doing wrong? Commenting out the `auto that...` and the for loop makes the code compile just fine, and if I stick a `std::cout << typeid(cons).name() << '\n';` in there, I get `N5sdbus7VariantE`, which leads me to believe I'm just converting the property wrong?

**Comment by lukasdurfina** [comment]
Hi dieggsy,

the vector contains ObjectPath(s), so you have to use:
`auto that = cons.get<std::vector<sdbus::ObjectPath>>();`

You can use a method `peekValueType()` to get a type in the variant.
In that case, it is _ao_, what stands for array (vector) of object paths (`class ObjectPath : public std::string`)

**Comment by dieggsy** [comment]
Oh, sweet. I saw the peekValuetype(), but I guess I wasn't aware that object paths were converted to class Objectpath - is there a way to easily what the dbus type -> C++ type conversion is?

Thanks for the help. This library is much more intuitive to use than the alternatives I've found so far.
