### ISSUE TITLE
Handling in case of multiple clients and single server

### ISSUE THREAD

**Issue by vk-gst** [Kistler-Group/sdbus-cpp#185]
I would like to get some views on the usage of multiple clients interacting with a single server use case using sdbus-c++.  I have implemented an asynchronous client and synchronous server based sdbus-c++ application using convenience APIs. 

Now my server is supposed to interact with hardware APIs which behaves in a synchronous way. Hence the server application is designed to handle synchronous operations. This all works fine when there is one client proxy object. 

The scalability causes an issue in my design now, where there can be more than one client who want to interact with the same server instance. In this case, how should I design the application. The issue I face is when the same exposed interface/API is called parallely by two client proxies and only one of them is accepted by the server. 

How would the sdbus-c++ design handle such a case? 
Spawning new thread for each client proxy would be an ideal case here? Or is there some other approach that works best for sdbus-c++?

**Comment by sangelovic** [comment]
@vk-gst I think I don't fully understand your issue. Your D-Bus server ignores the request from the second client? Or your server takes too long to serve the request from the first client, and the second client's request times out in between?

In general, sdbus-c++ fetches and serves incoming messages (e.g. requests from clients) serially, one by one, on a FIFO basis. That is, while a request from client A is being served, request from client B that comes in the meantime is enqueued and served after client A's request has been served. So no request should be ignored (but a request may time out, for example, if the server is busy handling previous request and a timeout threshold is reached).

In addition to client side, sdbus-c++ provides an API to support async serving on server side. That is described, including examples, in the tutorial: https://github.com/Kistler-Group/sdbus-cpp/blob/master/docs/using-sdbus-c%2B%2B.md#asynchronous-server-side-methods .

This enables your implementation of the server to serve the requests in parallel, in separate threads, without blocking the processing of other requests while previous requests are still being served. This however, if I understand your situation correctly, may not be the solution for your if access to the HW that the server interacts with must be serialized anyway. The threads would anyway need to be serialized and would block each other.

**Comment by vk-gst** [comment]
@sangelovic : 
I would like to modify my design in the following way to accomodate the handling:

1. Asynchronous DBus client methods using `callMethodAsync` (convenience APIs)
2. Synchronous handling at the server by using a `std::queue`, which queues up all the request received at the server. A separate thread that checks the queue, then executes the requests sequentially and later invokes the appropriate callbacks.

Would you reccommend such a design for handling the usecase, or does the DBus internally serialize at the server end? 
My interaction with hardware APIs, can take some time and during this period, I would still want the client to receive further requests, that is passed on to the server and executed after the previous request is completed. 

P.S. I have already implemented the whole design using synchronous client-server and it works perfectly fine. However, the next step is to enable parallel handling of client requests,  and then invoke callbacks for specific requests once the execution is completed.

**Comment by vk-gst** [comment]
Here is a pseudo code to better explain the problem:

```
//server.h
// The Server runs as an independent service 

class Server
{
   Server();
   ~Server();
   
   void init()
   { 
        m_connection = sdbus::createSystemBusConnection(DBusInterface::gServiceName);
        m_object = sdbus::createObject(*m_connection, DBusInterface::gObjectPath);
	m_object->registerMethod("sendRequestA").onInterface(INTERFACE_NAME).implementedAs([this]() {
             std::unique_lock<std::mutex> lock(m_QueueMtx);
             m_ProxyReqQueue.push([this]() {
                 const uint8_t status= static_cast<uint8_t>(m_HardwareInstance.RequestA());    //requestA returns a status.
                 return status;
            });
            lock.unlock();            
        });
   }
   
   private:
        std::unique_ptr<sdbus::IConnection> m_connection;
	std::unique_ptr<sdbus::IObject> m_object;
	std::queue<std::function<void(void)>> m_ProxyReqQueue;
        std::mutex m_QueueMtx;
        HardwareInstance m_HardwareInstance;
}
```


```
#client.h 
//class to be inherited for using 
class Client
{ 
    Client();
    ~Client();

    void sendRequestA() 
    {  
       //use DBus async call to send request to server
	m_Proxy->callMethodAsync("sendRequestA").onInterface(INTERFACE_NAME)
          .uponReplyInvoke([this](const sdbus::Error* error, const uint8_t& status) {this->replyCallbackA(status);});  
    }

    void sendRequestB() {...}
    
    protected:
    virtual void replyCallbackA(const uint8_t& status) = 0 ; // ... callback invoked by the DBus server   
    virtual void replyCallbackB(const uint8_t& status) = 0 ;
}

```

**Comment by vk-gst** [comment]
closing the issue, as the handling of async DBus is clear.

**Comment by sangelovic** [comment]
@vk-gst Sorry for late reply. Yes you are right, sdbus-c++ automatically queues incoming method calls on the server side. You don't need to queue them yourself. It serves one request, while next request wait in the queue. After that request has been served, it will fetch and serve the next one (if there's any; if not, it will wait for incoming requests). One by one. There is no parallelism (unless you want it -- but then you do it yourself, with the help of sdbus-c++' async server API).
Parallelism on the client side is something different. There you don't care about how it's done on the server side. You just issue a request and provide an associated callback handler, and continue with other stuff of yours, and when the reply comes from the server, the callback will be invoked. You don't block waiting for the reply in your code, you are free to do whatever other stuff you want in the meantime.
