### ISSUE TITLE
Support using system googletest

### ISSUE THREAD

**Issue by bachp** [Kistler-Group/sdbus-cpp#188]
Currently sdbus-c++ always fetches google test by itself.

This requires upstream to patch the source to disable this. One example is in OE: http://cgit.openembedded.org/meta-openembedded/commit/meta-oe/recipes-core/sdbus-c++?id=6c74740048a6a8413e10b4f29164a38d85020877

A better way would be to provide an option to support system provided one and try to find it with `find_package`.

**Comment by sangelovic** [comment]
Hi Pascal, thanks, master has that already: https://github.com/Kistler-Group/sdbus-cpp/blob/master/tests/CMakeLists.txt#L8
sdbus-c++ searches for system-provided googletest, first it tries through `find_package`, then through `pkg-config`, then in the last step it resorts to fetching and building one.

This change has not been released yet.

**Comment by sangelovic** [comment]
The fix is part of the v1.0.0 release. Meta-openembedded recipe has also been updated: https://github.com/openembedded/meta-openembedded/commit/b26b66e5da92718b4e99a57fbfaaef9e751c3cfe
