### ISSUE TITLE
Access to proxy member after proxy object has been deleted

### ISSUE THREAD

**Issue by 10sor** [Kistler-Group/sdbus-cpp#199]
Hello, I search a library for communication via DBus. After reading your docs I've observed source code a little bit and have a question about safe usage of convenience API. Below we have a class from examples, I just suspect that if the user deletes it while handling "onConcatenated" invalid memory will be accessed. I think so because I saw that the event loop thread joins in the destructor of the Connection (which resides in ProxyInterfaces) class. Can you confirm it or prove that I'm wrong here Thanks in advance.

```#include <sdbus-c++/sdbus-c++.h>
#include "concatenator-client-glue.h"

class ConcatenatorProxy : public sdbus::ProxyInterfaces<org::sdbuscpp::Concatenator_proxy /*, more proxy classes if there are more interfaces*/>
{
public:
    ConcatenatorProxy(std::string destination, std::string objectPath)
        : ProxyInterfaces(std::move(destination), std::move(objectPath))
    {
        registerProxy();
        m_data = std::make_unique....
    }

    ~ConcatenatorProxy()
    {
        unregisterProxy();
    }

protected:
    void onConcatenated(const std::string& concatenatedString) override
    {
        std::cout << "Received signal with concatenated string " << concatenatedString << std::endl;

        std::this_thread::sleep_for(std::chrono::seconds(5));

        // imagine that destructor ConcatenatorProxy already called here and Connection joins event loop thread in Destructor, so the m_data deleted here

        m_data->Update();
    }

private:
    std::unique_ptr<Data> m_data;
};

**Comment by sangelovic** [comment]
This is safe and what you fearz can't happenz,by design.

Please, in the future, create a GitHub issue only when you have a real issue to report. Otherwise, for questions or for (in)validating your feelings, please use GitHub Discussions section.

**Comment by 10sor** [comment]
I am new on GitHub, sorry for posting in the wrong place. I just try to find out how the lib works under the hood to be able to contribute and fix possible bugs in the future.

**Comment by sangelovic** [comment]
No problem. To go little into details in my answer, whenever most of the
underlying sd-bus functions are used, a sd-bus mutex is locked. How the
case you've mentioned works is that this mutex is locked while a D-Bus
signal handler is being invoked. If another thread tries to destroy the
Proxy instance simultaneously, the releasing of Proxy's internal handler
slots will take place, which will unregister the handler from sd-bus, but
for that it has to lock the same mutex. So the thread will wait until
currently executed handler has finished, and then safely proceed with Proxy
destruction.

**Comment by 10sor** [comment]
Thanks a lot for the explanation.
