### ISSUE TITLE
fails to compile on artiz

### ISSUE THREAD

**Issue by emmatebibyte** [Kistler-Group/sdbus-cpp#201]
artix* I butterfingered the enter key.

```CMake Error at /home/emma/.cache/paru/clone/sdbus-cpp-nosystemd-git/src/build/libsystemd-v242/src/LibsystemdBuildProject-stamp/LibsystemdBuildProject-configure-Release.cmake:49 (message):
  Command failed: 1

   '/usr/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/emma/.cache/paru/clone/sdbus-cpp-nosystemd-git/src/build/libsystemd-v242/src/LibsystemdBuildProject-stamp/LibsystemdBuildProject-configure-Release-impl.cmake'

  See also

    /home/emma/.cache/paru/clone/sdbus-cpp-nosystemd-git/src/build/libsystemd-v242/src/LibsystemdBuildProject-stamp/LibsystemdBuildProject-configure-*.log


make[2]: *** [CMakeFiles/LibsystemdBuildProject.dir/build.make:92: libsystemd-v242/src/LibsystemdBuildProject-stamp/LibsystemdBuildProject-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:174: CMakeFiles/LibsystemdBuildProject.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().```

**Comment by eiffel-fl** [comment]
Hi.

I had the same error, checking the log puts me on the way:

```
Program gperf found: NO

meson.build:655:0: ERROR: Program(s) ['gperf'] not found or not executable
```

I just had to install gperf:

```
you@home$ sudo apt install gperf
```

And then I was able to build `sdbus-cpp`  with `libsystemd`.
Nonetheless, `gperf` is not listed in the dependencies of `libsystemd`:

> That includes meson, ninja, git programs and mainly libraries and library headers for libmount, libcap and librt (part of glibc)

Would a PR with update to this part of the documentation would be welcomed?

Best regards.

**Comment by sangelovic** [comment]
@emmatebibyte @eiffel-fl I've added `gperf` dependency explicitly to the list in the documentation and to the CMake file, so now it fails with direct message from sdbus-c++ configuration. Thanks for details and your offer @eiffel-fl. I'll now close this issue.
