### ISSUE TITLE
UNABLE TO RUN ON SYSTEMBUS --- [URGENT]

### ISSUE THREAD

**Issue by leocorp96** [Kistler-Group/sdbus-cpp#212]
I am unable to run the basic service server example when using the SystemBus. I get this error when running normally:
terminate called after throwing an instance of 'sdbus::Error'
  what():  [org.freedesktop.DBus.Error.AccessDenied] Failed to request bus name (Permission denied)
Aborted (core dumped)

It however runs without errors when using sudo. But that is because I have also created the .conf file @ 
/etc/dbus-1/system.d/org.sdbuscpp.concatenator.conf
with content:
<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <policy user="root">
    <allow own="org.sdbuscpp.concatenator"/>
    <allow send_destination="org.sdbuscpp.concatenator"/>
    <allow send_interface="org.sdbuscpp.Concatenator" send_member="concatenate"/>
  </policy>
</busconfig>

But still doesn't work as it should. The service shows up on D-Feet or busctl but I am unable to do anything with it. It just pops up an error message. Also neither, does the client work. Something about not being able to register the signal and method. I beleive this is due to the fact that the Proxy object isn't bound to any service in particular.

**Comment by leocorp96** [comment]
I figured it out. If anyone else has the same issue, this is what I did for the "Concatenate" example in the tutorial:

First create the conf file and name it as follows:
/etc/dbus-1/system.d/**org.sdbuscpp.concatenator.conf**

And populate the newly created file with:

`<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <policy user="your_user_name_here_not_root">
    <allow own="org.sdbuscpp.concatenator"/>
    <allow send_destination="org.sdbuscpp.concatenator"/>
    <allow send_interface="org.sdbuscpp.Concatenator" send_member="concatenate"/>
  </policy>
</busconfig>`

Your may probably need to restart your terminal or just reload config.

**Comment by sangelovic** [comment]
The [tutorial](https://github.com/Kistler-Group/sdbus-cpp/blob/master/docs/using-sdbus-c++.md#an-example-number-concatenator) mentions this, providing a link to a specific markdown page describing the needed configuration.

**Comment by philippludwig** [comment]
Yeah it mentions this, but the information by leocorp should be incorporated into the tutorial.
