### ISSUE TITLE
Update meta-oe recipes to version 1.0.0

### ISSUE THREAD

**Issue by hellow554** [Kistler-Group/sdbus-cpp#213]
1.0.0 has been released 🎉 

It would be nice if the files in the meta-openembedded repository could be updated to reflect the update: https://github.com/openembedded/meta-openembedded/tree/master/meta-oe/recipes-core/sdbus-c%2B%2B

I don't know why and how libsystemd is used as a dependency and with so many patches, so I won't touch it ;)

**Comment by sangelovic** [comment]
Done: https://github.com/openembedded/meta-openembedded/commit/b26b66e5da92718b4e99a57fbfaaef9e751c3cfe
