### ISSUE TITLE
Unregister signal handler - Client Side

### ISSUE THREAD

**Issue by osamaghanem** [Kistler-Group/sdbus-cpp#214]
The client can register a call back handler for any signal but he couldn't unregister it without unregistering everything!
Is there a reason for the current interface design?
I have an easy work-around to provide this feature, my proposal goes as follows:

1. Add a **virtual** method to the `IProxy` interface:
`virtual void unregisterSignalHandler( const std::string& interfaceName, const std::string& signalName ) = 0;`

2. Implement it in the `Proxy` class as removing the relevant entry from the `signals_` map of the given interface.
3. Add a `clear()` method to the `SignalSubscriber` class that call the unregister method.

**Use case:**
`auto subscriber = m_proxy->uponSignal("some_signal").onInterface("some_interface");`
`subscriber.call(some_handler); // register handler`
`// ........`
`// ........`
`subscriber.clear(); // unregister handler`

If my proposal looks good and doesn't break any thing I can create a pull request for this issue.

**Comment by sangelovic** [comment]
@osamaghanem There is no specific reason behind that, other than that kind of flexibility was not needed. With generated proxy classes, there is 1:1 relation to everything that the counterpart remote object provides, and it's not changeable at runtime. A proxy connects a "slot" to the object's signal and reacts. No reaction emulates "there is no callback handler" behavior. 

However, it is true that this runtime behavior is changeable at the convenience API level and lower. Technically, there is no problem with having the support for unsubscription. However, `SignalSubscriber` is not a good place for that. First, it's not designed to be used as a named object (unlike in your use case example), but as a temporary anonymous object that is hidden behind a chain of calls. Second, it's been designed for subscribing action.

Feel free to create a PR with the `virtual void IProxy::unregisterSignalHandler( const std::string& interfaceName, const std::string& signalName ) = 0;` you proposed. And, probably also with a dedicated new auxiliary class `SignalUnsubscriber`, which would be used like: `m_proxy->uponSignal("some_signal").onInterface("some_interface").doNothing()` (a good counterpart to upon signal x - on interface y - call z) or, alternatively, `m_proxy->unsubscribeFromSignal("some_signal").onInterface("some_interface")`. I think I like the former a bit more.

What are your thoughts? Would you prepare such a PR?

**Comment by osamaghanem** [comment]
@sangelovic I do agree with you not to use `SignalSubscriber` as a named object, but if we want to provide your preferred usage: `m_proxy->uponSignal("some_signal").onInterface("some_interface").doNothing()`, we just need to rename the `clear()` method to `doNothing()` in my proposal , thus the new auxiliary class `SignalUnsubscriber` is useless here, am I right?
