### ISSUE TITLE
Update conan center version to 1.0.0

### ISSUE THREAD

**Issue by aacebedo** [Kistler-Group/sdbus-cpp#219]
Hi !

I was wondering if the recipe on conan-center could be updated to 1.0.0. Do you have the ownership of it ?
(https://conan.io/center/sdbus-cpp)

**Comment by sangelovic** [comment]
@aacebedo Hi, no I don't own that recipe... Are you familiar with conan? Is there a way to contact the author or contribute the change directly?

**Comment by aacebedo** [comment]
yes I am familiar with but never published on the center.  I guess only the owner can update this.

**Comment by aacebedo** [comment]
It's here. I'll do the PR on their repo.
https://github.com/conan-io/conan-center-index/tree/master/recipes/sdbus-cpp

**Comment by sangelovic** [comment]
@aacebedo That would be great. Feel free to cc me in that PR, if possible

**Comment by aacebedo** [comment]
Here is the PR  https://github.com/conan-io/conan-center-index/pull/8440
There is a little thing to do on your CMakeLists.txt to be able to use your release archive out of the box.
Can you take a look ?

**Comment by sangelovic** [comment]
@aacebedo great. You probably mean the change in this PR: https://github.com/Kistler-Group/sdbus-cpp/pull/227, right? I'll try to speed it up.

**Comment by aacebedo** [comment]
Let me know when you release a new version I'll update the Conan recipe.

**Comment by sangelovic** [comment]
Ok, it would be good to have the two remaining open PRs merged, too, and then release a new version. I'll let you know.

**Comment by sangelovic** [comment]
@aacebedo You are good to go :) We have a new version -- v1.1.0 :)

**Comment by aacebedo** [comment]
Great ! I update it. Keep you posted

**Comment by aacebedo** [comment]
PR is here waiting for merge https://github.com/conan-io/conan-center-index/pull/8573
