### ISSUE TITLE
Unused integrationtest File with duplicated tests

### ISSUE THREAD

**Issue by riuriuriu** [Kistler-Group/sdbus-cpp#225]
The file [tests/integrationtests/AdaptorAndProxy_test.cpp](https://github.com/Kistler-Group/sdbus-cpp/blob/v1.0.0/tests/integrationtests/AdaptorAndProxy_test.cpp) is not listed in any CMake file and not compiled. Most but not all of it's tests are duplicated in other test files like i.e. `DBusMethodsTests.cpp`.

@sangelovic Can we delete this file? Should any tests be moved out before deletion?

**Comment by sangelovic** [comment]
@riuriuriu Good catch Urs, I've refactored and split this file into several distinct files, and looks like I forgot to remove it back then. I've deleted it now in master.
