### ISSUE TITLE
Enable move for ObjectPath and Signature.

### ISSUE THREAD

**Issue by BenKaufmann** [Kistler-Group/sdbus-cpp#230]
With commits https://github.com/Kistler-Group/sdbus-cpp/commit/c1c4512f and https://github.com/Kistler-Group/sdbus-cpp/commit/0090ca97 ObjectPath and Signature both gained a _user-declared_ copy-ctor and copy-assignment operator. While this seems to fix some issue with older compilers, it also means that corresponding move operations are no longer implicitly created by the compiler. 
Hence, moving an ObjectPath or Signature will actually result in a call to the copy-ctor/copy-assignment operator.

A simple fix would be to explicitly add _default_'ed versions of the move operations (e.g. https://github.com/raumfeld/sdbus-cpp/commit/7ad570ec7ace7ab0dc49d977090d3124707de02f)

**Comment by sangelovic** [comment]
@BenKaufmann You are right. Would you please open a PR for this?
