### ISSUE TITLE
Potential undefined behaviour in creation of sdbus::Error

### ISSUE THREAD

**Issue by BenKaufmann** [Kistler-Group/sdbus-cpp#231]
At least ` MethodCall::sendWithReply()` and `Proxy::sdbus_async_reply_handler()` create an sdbus::Error object from an `sd_bus_error` object **without** ensuring that the contained **optional** `message` is set (i.e. != `nullptr`). Hence, if the message field is not set, the code tries to create a `std::string` from a `nullptr`, which has undefined behaviour.

Note that e.g. `sd_bus_error_set` **explicitly** allows using `nullptr` to mean "no message".

One simple fix would be to add a second constructor overload: 
```cpp
Error(const std::string& name, const char* message)
  : Error(name, std::string(message ? message :  ""))
{
}
```

**Comment by sangelovic** [comment]
@BenKaufmann Good point. Would you file a PR here, too?
