### ISSUE TITLE
Cannot listen to signals from "anonymous" senders.

### ISSUE THREAD

**Issue by mgruhler** [Kistler-Group/sdbus-cpp#257]
With PR #170, which solved #145, another filter has been added in `std::string Connection::composeSignalMatchFilter(...)` which populates the `sender` field for the match.
This has the effect, that only senders that provide a well-known name can be reproducibly reached.

@dleeds-cpi  commented in the associated PR:
> @riuriuriu I have in the past observed issues where the `sender` field is populated with the unique bus ID, and not the service's well-known name. If this were to occur, these changes would filter out all signals. Unfortunately, I do not recall exactly what version of the D-Bus Daemon was in use, or whether the offending signals were emitted by `sd-bus` or a different D-Bus library.
> 
> Have you tested these changes with a variety of client library versions and D-Bus daemons?

I think I've now found another (or a similar) instance of this. The [`gpsd` daemon](https://gpsd.gitlab.io/gpsd/gpsd.html) provides a (very minimal) DBus interface by sending out a signal. It does, however, not request a well-known name [(see source for reference)](https://gitlab.com/gpsd/gpsd/-/blob/master/gpsd/dbusexport.c).

So ultimately, the only way to listen to this signal using sdbus-cpp right now is to use the unique bus name.
Not sure if/how this could be properly solved while still keeping the patch from #170 intact. Just though I'll report this minor limitation here.

**Comment by sangelovic** [comment]
Hi @mgruhler, sorry for little late reply -- busy as always ;) In sdbus-c++, you can't create a proxy object to a remote object without knowing where it lives. You have to provide `destination` argument (be it well-known name or not) when constructing a proxy object. This is then used for signal match rule, to only get signals from that specific remote object. I think what would give you a tool to subscribe to such signals yourself as sdbus-c++ client is a feature proposed in comments here: https://github.com/Kistler-Group/sdbus-cpp/discussions/258. With this you could assemble the match rule however you like (given what the source daemon provides to you) and listen to matching signals without having to construct a proxy object.

**Comment by mgruhler** [comment]
Hi @sangelovic 

no worries. Thanks for your response.
I agree that usually you should know what to listen for, and that the "old" behavior was bsically misusing the Proxies.
#258 seems to be to exactly what would allow us to do what we want. AND fall more in line with what a Proxy is supposed to be. Even though one could ultimately argue that the specific instance of the gpsd daemon could also be considered a "bug" in the daemon itself :-)

I'll close this issue, as I think the discussion in #258 is more on point already.

Thanks for you work on this project :clap:
