### ISSUE TITLE
non-root user cannot request systembus name

### ISSUE THREAD

**Issue by kodiakz** [Kistler-Group/sdbus-cpp#259]
For an application in a yocto project I replaced the existing _gdbus_ implementation with a 1:1 implementation of _sdbus-c++_. Requesting the bus name results in 

 **[Received std::exception:  [org.freedesktop.DBus.Error.AccessDenied] Failed to request bus name (Permission denied)]**

_DBus policy_, _DBus service_ is **untouched**, the application is getting started via _SystemD service_ which is also **untouched**, and runs as user and group:

```
[Service]
User=someuser
Group=someuser
```

The lines in question:
```
const std::string SOMESERVICE_WELLKNOWN_NAME ("com.some.service");
m_sdbusConnection = sdbus::createSystemBusConnection();
m_sdbusConnection->requestName(SOMESERVICE_WELLKNOWN_NAME);
```

SystemD: _v241-stable_
sdbus-c++_1.0.0.bb from _Kirkstone_ with commit _65782bbf435d91e5eb6af9ddab110df406a824a9_

content of _/etc/dbus-1/system.d/com.some.service.conf_
```
<busconfig>
  <!-- ../system.conf have denied everything, so we just punch some holes -->
  <policy user="someuser">
    <allow own="com.some.service"/>
    <allow send_destination="com.some.service"/>
    <allow send_interface="com.some.service"/>
  </policy>

   <!--  **works with sdbus-c++ only if applied, works with gdbus without** -->
   <policy user="root">
     <allow own="com.some.service"/> 
   </policy>

  <!-- allow users at the console, see consolekit o-->
  <policy at_console="true">
    <allow send_destination="com.some.service"/>
  </policy>

  <!-- allow users of some group (printing subsystem)  -->
  <policy group="someuser">
    <allow send_destination=""com.some.service"/>
  </policy>

  <policy context="default">
    <deny send_destination=""com.some.service"/>
  </policy>
</busconfig>
```

I am getting the app only running when I add the policy owner ship for **root explicitly**. The app worked with _gdbus_ without that need, and the _application is not running as root_ at all.

```
ps -ef | grep someservice
someuser           677    1    2 00:00 ?        00:00:00 /usr/bin/someservice
root               884    328  0 00:00 ttymxc0  00:00:00 grep someservice
```
```
someservice.service - SomeService
   Loaded: loaded (/lib/systemd/system/someservice.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 1970-01-01 00:00:27 UTC; 7min ago
 Main PID: 677 (someservice)
    Tasks: 2 (limit: 1785)
   CGroup: /system.slice/someservice.service
           └─677 /usr/bin/someservice

Jan 01 00:00:27 machine systemd[1]: Started SomeService
Jan 01 00:00:33 machine someservice[677]: Starting SomeService
```
```
systemctl show -pUser,UID someservice
UID=770
User=someuser
```

_**Simple question: what is wrong with the setup, thus root is needed as bus owner in the policy?**_

**Comment by kodiakz** [comment]
I had a typo issue in another policy file which caused that behavior. After applying the fix the system bus can now be acquired by _someuser_.

**Comment by sangelovic** [comment]
@kodiakz Sorry for coming late to the party. What kind of typo did you have in another policy file that affected policy for `com.some.service`?
