### ISSUE TITLE
Is there a way to create `PlainMessage`s without a bus connection?

### ISSUE THREAD

**Issue by JohannesSchilling** [Kistler-Group/sdbus-cpp#277]
[sorry if this is more of a support request than a regular issue, i guess you could phrase it as "please document" instead though]

During unit-testing of my code i've come across the need to create `sdbus::PlainMessage`s as test input. I didn't find a way to create them so they are valid/usable without having an actual D-Bus daemon running (i.e. `operator>>` would fail without D-Bus connection). Is there something i'm missing here, or is this not a supported use-case?

**Comment by sangelovic** [comment]
Yes, plain messages (and thus `Variant`) need a D-Bus connection object to work. But your question led me to re-think an older idea of introducing a solution that creates a "pseudo" bus connection that doesn't really connect to the D-Bus daemon, but as such can be used to create messages to work with locally. It's a bit of a hacky solution, but I hope it's worth it. See MR #280

**Comment by Kleist** [comment]
As far as I can tell it is not possible to use the new `createPlainMessage` introduced in #280 because it is not declared in a public header file. Am I missing something? Would there be anything wrong with exporting it?

Sorry for posting on an old closed issue, but I think this is relevant.

**Comment by sangelovic** [comment]
@Kleist Can you elaborate a little what benefits would you get as a client from using such a plain message, what is the problem that you're solving?

**Comment by Kleist** [comment]
I'd like to use it for unit testing serialization and deserialization of my custom structs. Maybe there is some better way?

**Comment by sangelovic** [comment]
@Kleist It's in master (v2 branch) now. Do you also want it in v1.x?
And Is it OK like this or do you want me to create a new tag (version?)

**Comment by Kleist** [comment]
Thank you for the quick fix. I will only be using v2, so that is fine.
There's no hurry tagging a version from my point of view, but of course it would be nice to have at some point.
