### ISSUE TITLE
Doxygen html includes reference to build directory by default

### ISSUE THREAD

**Issue by Thaodan** [Kistler-Group/sdbus-cpp#288]
The html files generated by doxygen include a reference to the build directory by default.
E.g. if the build directory was _/build/sdbus-cpp_ every file that references source code that path.

**Comment by sangelovic** [comment]
@Thaodan Do you suggest a specific fix? Would you submit a PR with it?

**Comment by Thaodan** [comment]
My hack for this was do to this after install:
```
    # Remove references to $srcdir
    find "$srcdir/fakeinstall/usr/share/doc" -name \*.html -print -exec sed \
         -e "s|${srcdir}/sdbus-cpp/include|/usr/include|g" \
         -e "s|${srcdir}/sdbus-cpp||" \
         -i {} \;
```

But setting _FULL_PATH_NAMES_ to no or using _STRIP_FROM_PATH_ in 
Doxygenfile.in might help.

I would at least replace the header files to mentioned the real path of the 
install e.g. _/usr/include_ instead of the build directory.
