### ISSUE TITLE
Occuring exception when calling sdbus::internal::Connection::openBus(std::function<int(sd_bus**)> const&)()

### ISSUE THREAD

**Issue by mjunjun** [Kistler-Group/sdbus-cpp#332]
**Describe the bug**
Proxy init,but occuring exception when calling sdbus::internal::Connection::openBus(std::function<int(sd_bus**)> const&)()
Why this exception raise? Is it related to dbus-daemon?

**To Reproduce**
using the systemd start process,but the process occuring exception when calling sdbus::internal::Connection::openBus(std::function<int(sd_bus**)> const&)().
proxy init failed.

**Expected behavior**
there is no exception occured when proxy init.

**Real (buggy) behavior**
occuring a exception when using openBus

**Comment by sangelovic** [comment]
Hi, I need more information in order to help you. The most likely cause is that the application can't connect to dbus-daemon. Are you sure you have a working dbus daemon? Have you followed these steps: https://github.com/Kistler-Group/sdbus-cpp/blob/master/docs/systemd-dbus-config.md ?
