### ISSUE TITLE
Crash in createPlainMessage() when invoked while application is exiting

### ISSUE THREAD

**Issue by pawelwod** [Kistler-Group/sdbus-cpp#333]
The [createPlainMessage() function](https://github.com/Kistler-Group/sdbus-cpp/blob/c39bc637b8df7791c697c7e75f1376ac0a9b9678/src/Message.cpp#L872C23-L872C23) holds pseudo connection object in `unique_ptr` local static variable. When application starts exiting the global destructors gets called. Order of global destructors invocation is defined only for single translation unit. This in turn opens possibility that the globals of sdbus-cpp library gets destroyed first and the `static auto connection` variable from mentioned function is gone.

Next, the upper layers (e.g.: application) destructors will be invoked. At this moment the application might want to issue DBUS request using this library (it might still hold valid connection objects). If this happens it will crash during construction of `Variant` object when `createPlainMessage()`  is called.

Call stack is:
```
sdbus::createPlainMessage()
sdbus::Variant::Variant()
sdbus::PropertyGetter::onInterface() at ConvenienceApiClasses.inl:701
```

**Comment by sangelovic** [comment]
@pawelwod The design of your application which uses globals for such operations is questionable, but I agree that the library shall not be unpredictable regarding lifetime for its internal objects. I prepared a MR #336 to fix this.
