### ISSUE TITLE
Build system fails to detect elogind

### ISSUE THREAD

**Issue by Apteryks** [Kistler-Group/sdbus-cpp#351]
**Is your feature request related to a problem? Please describe.**
I'm trying to build sdbus-cpp for a system which lacks systemd proper, and ships with elogind instead.

**Describe the solution you'd like**
The build system should fallback to detect  and use elogind if systemd is not available.

**Additional context**
See https://github.com/elogind/elogind/issues/190#issuecomment-752414489 for some idea about the implementation.

**Comment by sangelovic** [comment]
Fixed with #352
