### ISSUE TITLE
Building statically but linking to a shared library results in linker error

### ISSUE THREAD

**Issue by proatgram** [Kistler-Group/sdbus-cpp#357]
**Describe the bug**
When compiling the library with `BUILD_SHARED_LIBS` set to `OFF`, and then linking to an output target that compiles their libraries as shared, we get linker errors due to the `-fPIC` option not being set in compile arguments.

**To Reproduce**
Create a CMake project that pulls in sdbus-cpp as a subproject, and compile that as static by setting `BUILD_SHARED_LIBS` to off. Then create a shared library in the top CMake project and link sdbus-cpp to it.

**Expected behavior**
In my project, I set `CMAKE_POSITION_INDEPENDENT_CODE` to `ON`. I expect this value to carry through to this project.

**Additional context**
OS: Arch Linux
SDBus version: v1.3.0

This line seems to be the culprit, setting the `POSITION_INDEPENDENT_CODE` variable to the value of `BUILD_SHARED_LIBS`
In this context, it is being set to off, even though this option is needed to link the statically compiled sdbus-c++ to shared libraries.
https://github.com/Kistler-Group/sdbus-cpp/blob/0eda85574546d19d9f06d6d5418bc192b3846f96/CMakeLists.txt#L123

**Comment by sangelovic** [comment]
@proatgram Thanks for reporting. Please feel free to review #361 and let me know if that works fine for you.

**Comment by proatgram** [comment]
> @proatgram Thanks for reporting. Please feel free to review #361 and let me know if that works fine for you.

Sorry for the late reply, been pretty busy.
Yes, this works. Thank you!
