### ISSUE TITLE
Implementation lacks naming of method arguments

### ISSUE THREAD

**Issue by caco3** [Kistler-Group/sdbus-cpp#36]
The dbus Introspector is able to show the names of the arguments of a method.
Example with connman:
```
> dbus-send --system --type=method_call --dest=net.connman --print-reply / org.freedesktop.DBus.Introspectable.Introspect
[..]
<method name="RequestPrivateNetwork">
 <arg name="path" type="o" direction="out"/>
 <arg name="settings" type="a{sv}" direction="out"/>
 <arg name="socket" type="h" direction="out"/> </method>
[..]
```

The relevant code for this seems to be in https://git.kernel.org/pub/scm/network/connman/connman.git/tree/src/manager.c#n576

sdbus-c++ seems to lack this naming!
See example below where it only show the arguments but not the name tag:
```
  <method name="getData">
   <arg type="u" direction="in"/>
   <arg type="b" direction="in"/>
  </method>
[..]
```

The xml code is as following:
```
      <method name="getData">
         <arg type="u" name="timestamp" direction="in" />
         <arg type="b" name="absoluteTimestamp" direction="in" />
      </method>

```

**Comment by caco3** [comment]
After some more investigation, we learned that a possible fix not only relies on `sdbus-cpp` but also on `libsystemd`!

This is the code path we traced down:
1.  libsystemd has a table (sd_bus_vtable) where the methods arguments (signatures) are stored. This table would have to be extended to not only contain the signatures but also the arguments names.
2. The table gets filled by the macro function SD_BUS_METHOD() 
3. That macro function gets called by sdbus-cpp in https://github.com/Kistler-Group/sdbus-cpp/blob/master/src/VTableUtils.c#L35

Side note:
There are methods of services using libsystemd which provide the arguments name. How ever this seems all to be hardcoded into the code:
https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-bus/bus-protocol.h#L131

**Comment by sangelovic** [comment]
Hi George,

very good point. And, as you found out, the introspection of each D-Bus object is implemented by underlying sd-bus itself. It has all the information about each D-Bus interface from its registered methods, signals and properties. All but one piece -- names of method parameters.

I asked about that at the systemd mailing list here: https://lists.freedesktop.org/archives/systemd-devel/2019-February/042173.html

Let's see.

**Comment by sangelovic** [comment]
So there already has been discussion on this topic in sd-bus community, and a pull request https://github.com/systemd/systemd/pull/11357 with above-described functionality is ready to be merged. It is set to be part of the v242 milestone, which will be released in a few months. After the release, we can extend sdbus-c++ to conditionally use the new sd-bus API when it's available (sd-bus version >= 242), and fallback back to current mechanism if not available.

The issue may stay opened in the meantime.

**Comment by caco3** [comment]
Hi Stano

Thank you very much for tracing this down!

**Comment by sangelovic** [comment]
FYI, systemd [v242](https://github.com/systemd/systemd/blob/v242/NEWS) was released a few days ago. This version supports names of method parameters in introspection. It takes some time until this version gets to Linux distributions and until it gets to your platform, but since now we (Vlado, or I) are technically able to adapt sdbus-c++ for this new sd-bus introspection API.
