### ISSUE TITLE
Support for creating tcp connections via sd_bus_set_address or sd_bus_set_fd

### ISSUE THREAD

**Issue by anthonybrandon** [Kistler-Group/sdbus-cpp#371]
**Is your feature request related to a problem? Please describe.**

Currently it's possible to create remote connections using `sd_bus_open_system_remote`, this relies on the systemd dbus
bridge running on the target. It's then not possible to establish a connection when using freedesktop daemon with some other
authentication method than ssh.

**Describe the solution you'd like**

Add the ability to create a connection either with an `sd_bus_set_fd`, or `sd_bus_set_address`

**Describe alternatives you've considered**

None so far.

**Additional context**

If you think this feature is desirable and can get merged I can work on it and make a PR.

**Comment by sangelovic** [comment]
https://github.com/Kistler-Group/sdbus-cpp/pull/363 came with the possibility to construct an sdbus-c++ connection directly out of libsystemd's `sd_bus` object. This enables clients to use lower-level sd-bus API to create a bus object and configure it however they need, and then simply construct an sdbus-c++ bus connection (which among other things is anyway a wrapper of underlying `sd_bus*`) directly out of it.

Thanks to this, we don't have to create a plethora of various specific factory overloads, various wrappers of configuration functions from sd-bus, etc., for various specific needs.

I think this answers your question? You can use sd-bus API to construct a bus object you desire, and then create `IConnection` out of it.

**Comment by anthonybrandon** [comment]
Ah, sorry, didn't notice that one. Haven't looked at the commits in a few weeks. I'll have a look but think that should solve it.
