### ISSUE TITLE
Extend sdbus::ObjectPath constructor list to accept std::string as initializer

### ISSUE THREAD

**Issue by phatina** [Kistler-Group/sdbus-cpp#38]
Hey Stano,

please, extend `std::ObjectPath` ctors so that it can be also `std::string` constructed.

Now it has troubles doing so:
```
could not convert 'foo' from 'const string {aka const std::__cxx11::basic_string<char>}' to 'sdbus::ObjectPath'
```

Thanks a lot!

**Comment by sangelovic** [comment]
Thanks for reporting. Fixed in master.

**Comment by phatina** [comment]
Vielen Dank!
