### ISSUE TITLE
why: uncaught exception of type sdbus::Error ([org.freedesktop.DBus.Error.FileNotFound] Failed to open bus (No such file or directory))

### ISSUE THREAD

**Issue by Dhanush-gowda** [Kistler-Group/sdbus-cpp#413]
**Describe the bug**
I am Running my application in docker (debian 12 ) i have all the necessary libraries added but still i am facing system_dbus_socket issue .

Note : 1:  DBus available and running 
            2:  /usr/share/dbus-1/ has system.conf file 
            3: /var/run/dbus folder missing especially i am unable to find **system_bus_socket**  inside the folder 
            
**log file added** 
[run_carbon.log](https://github.com/Kistler-Group/sdbus-cpp/files/14416220/run_carbon.log)

**Below Logs for your reference :**

I have no name!@494fcfc0ba8e:~$ systemctl status dbus
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
I have no name!@494fcfc0ba8e:~$ ps aux | grep dbus-daemon
default       61  0.0  0.0   7852   436 ?        Ss   07:42   0:00 /usr/bin/dbus-daemon --syslog-only --fork --print-pid 6 --print-address 8 --session
default       90  0.0  0.0   8112  2524 ?        Ss   07:42   0:00 /usr/bin/dbus-daemon --syslog --fork --print-pid 6 --print-address 8 --session
default      121  0.0  0.0   8116  3616 ?        S    07:42   0:00 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 11 --address=unix:path=/headless/.cache/at-spi/bus_1
default      286  0.0  0.0   7976  2500 ?        Ss   07:42   0:00 /usr/bin/dbus-daemon --syslog --fork --print-pid 6 --print-address 8 --session
default      328  0.0  0.0   7852  3436 ?        S    07:42   0:00 /usr/bin/dbus-daemon --config-file=/etc/luaScriptRunner/dbus-config.conf --print-address
default      403  0.0  0.0   8988  3752 ?        S    07:42   0:00 dbus-daemon --config-file=/tmp/ncp/4115891742 --print-address
default      599  0.0  0.0   8988  3752 ?        S    07:42   0:00 dbus-daemon --config-file=/tmp/ncp/1917460568 --print-address
default      688  0.0  0.0   7972  2444 ?        Ss   07:43   0:00 dbus-daemon --session --address=unix:path=/tmp/oagw_dbus.socket --fork
1000         796  0.0  0.0   3396  1768 pts/2    S+   07:48   0:00 grep dbus-daemon
I have no name!@494fcfc0ba8e:~$ cat /var/log/syslog | grep dbus

**I have no name!@494fcfc0ba8e:/$ ls -alh /usr/share/dbus-1/**
total 48K
drwxr-xr-x 1 root root 4.0K Feb 24 18:05 .
drwxr-xr-x 1 root root 4.0K Feb 25 18:58 ..
drwxr-xr-x 2 root root 4.0K Feb 24 18:05 accessibility-services
drwxr-xr-x 1 root root 4.0K Feb 24 18:07 interfaces
drwxr-xr-x 1 root root 4.0K Feb 24 18:07 services
-rw-r--r-- 1 root root 3.5K Sep 16 10:03 session.conf
drwxr-xr-x 1 root root 4.0K Feb 24 18:07 system-services
-rw-r--r-- 1 root root 5.7K Sep 16 10:03 system.conf
drwxr-xr-x 1 root root 4.0K Feb 24 18:07 system.d

**Comment by sangelovic** [comment]
This doesn't look like the issue at the sdbus-c++ level. Please turn to the underlying sd-bus implementation used by sdbus-c++ in your system, most likely `systemd`. They have a mailing list here: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
