### ISSUE TITLE
Support for serializing `std::variant<>` types

### ISSUE THREAD

**Issue by anthonybrandon** [Kistler-Group/sdbus-cpp#422]
**Is your feature request related to a problem? Please describe.**
It would be useful to have serialization of `std::variant<>` directly in the library.

**Describe the solution you'd like**
`std::variant<>` can be serialized like an `sdbus::Variant`

**Describe alternatives you've considered**
I can have the serialization in my own code, but I think it's nicer if it's in the lib, like for array, vector, map, etc.

**Additional context**
I've made a PR #415. Let me know if you're interested in this feature or if it needs changes.

**Comment by sangelovic** [comment]
Hey @anthonybrandon, thanks for the PR, the idea sounds interesting, and yes, I started looking into that 2 weeks ago, but then I was interrupted. I will get back to this and let you know.

**Comment by sangelovic** [comment]
Solved in #415
