### ISSUE TITLE
SEGFAULT after generated proxy move

### ISSUE THREAD

**Issue by 17steen** [Kistler-Group/sdbus-cpp#434]
**Describe the bug**
if a proxy has been moved, anytime a signal is called, the program will segfault

**To Reproduce**
generate any proxy using the xml generator, instantiate proxy somewhere, move it, make it receive a signal, sefault

**Expected behavior**
do not segfault

**Real (buggy) behavior**
it segfaults

**Additional context**
a copy of the `this` pointer is made in the constructor, which is no longer valid after move
[the culprit](https://github.com/Kistler-Group/sdbus-cpp/blob/c769637f3b7d71fd05bd673359a2e988f3054efd/tools/xml2cpp-codegen/ProxyGenerator.cpp#L292)

**Comment by 17steen** [comment]
```cpp
   UPower_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
        proxy_->uponSignal("DeviceAdded").onInterface(INTERFACE_NAME).call([this](const sdbus::ObjectPath& device){
            this->onDeviceAdded(device);
         });
        proxy_->uponSignal("DeviceRemoved").onInterface(INTERFACE_NAME).call([this](const sdbus::ObjectPath& device){
            this->onDeviceRemoved(device);
         });
    }
```
par example if i generate this proxy based on Upower specification that gets notificed when a device is plugged in, the lambda in the constructor makes a copy of `this`, if i move this no longer works, kaput

my solution was to wrap my proxy in a unique_ptr, so i move the ptr, not the proxy itself.

**Comment by sangelovic** [comment]
Thanks for reporting, yes, this is a bug. Generated adaptor and proxy classes cannot be moveable. Your solution with `unique_ptr` is the recommended solution in case move support is needed (e.g. when the proxy or adaptor instances are stored in a container).

**Comment by sangelovic** [comment]
The fix will go into the soon-to-be-release `v2.0`.

**Comment by 17steen** [comment]
Thanks for the quick response @sangelovic,

It could still be possible to support moving by unregistering and re-registering, but not sure if that's worth the hassle

**Comment by sangelovic** [comment]
@17steen Yes exactly, that would not be worth the hassle.

One problem could be that there is a thin time window where e.g. object's vtable is not registered. What if a D-Bus call comes just within that window? It would fail on nonexisting object, while that object is actually existing, just that it's being moved.
Or in case of a proxy, it would not listen to signals for that short time, but what if an (important) signal comes just in that window and it is not caught..?

This would thus be a fragile, error-prone solution opening up more problems than fixing.
