### ISSUE TITLE
Ambiguous Template Instantiation when trying to use enum class with sdbus-cpp

### ISSUE THREAD

**Issue by fwilmsh** [Kistler-Group/sdbus-cpp#443]
First off wanted to give a quick shout-out to you guys. Really love the v2.0.0 release. It's great improvement in many areas, especially type stuff. Nevertheless I think I found something not working as expected:

**Describe the bug**
Following example will not compile with gcc 11.3 or gcc 11.4.
```#pragma once

#include "sdbus-c++/sdbus-c++.h"

enum class Member {
    FirstMember,
    SecondMember
};

struct Foo {
    Member bar;
};

SDBUSCPP_REGISTER_STRUCT(Foo, bar);
```

**To Reproduce**
Try to compile and/or use above code inside your application with sdbus-cpp.

**Expected behavior**
Code compiling and usable.

**Real (buggy) behavior**
It seems the [const Template redirect](https://github.com/Kistler-Group/sdbus-cpp/blob/e6b87b106c28f2318c31154ed20feb02b9cb3967/include/sdbus-c%2B%2B/TypeTraits.h#L136)
and the [enum template](https://github.com/Kistler-Group/sdbus-cpp/blob/e6b87b106c28f2318c31154ed20feb02b9cb3967/include/sdbus-c%2B%2B/TypeTraits.h#L340) both match for enum class in a struct. 

**Additional context**
I can workaround this behaviour by commenting the enum specific template and defining the signature template on my own.

**Comment by sangelovic** [comment]
And thanks for the nice feedback on v2.

**Comment by fwilmsh** [comment]
Works like a charm. Thanks for the quick help!
