### ISSUE TITLE
Add --version flag to xml2cpp to print out sdbus version

### ISSUE THREAD

**Issue by br337** [Kistler-Group/sdbus-cpp#460]
**Is your feature request related to a problem? Please describe.**
Since the output generated by the xml2cpp tool is dependent on the version of sdbus the tool has been built with, it would be nice to provide a way to print out the sdbus version for which the xml2cpp tool is working. 

**Describe the solution you'd like**
A --version flag to display the sdbus version for which the xml2cpp tool is generating code.

**Describe alternatives you've considered**
Not many alternatives other than hoping cmake finds the correct xml2cpp binary, while also making sure that multiple versions aren't installed on the host.

**Additional context**
Due to some limitations (cross compiling code and using the natively built xml2cpp tool as a build time dependency to generate the necessary adapter code) the xml2cpp can't easily be included as a cmake project using the find_package directive without building it from source and thereby having to build libexpat from source as well. This can be quite a hassle to do in a cross compilation environment and not strictly necessary. Thereby, the find_program cmake directive is used to lookup the xml2cpp tool. At the same time, one can't always be sure which exact xml2cpp binary version cmake has found. It would be helpful to have a --version flag that outputs the currently running version of the xml2cpp tool so that one can verify that the correct xml2cpp tool has been found by cmake during the project configuration.

**Comment by br337** [comment]
I could implement this myself and create a PR if the maintainers are okay with this. My solution would be a cmake generated header file that sets a define with the current version taken from the project version (by looking at the xml2cpp tool it seems that the tool's cmake project version follows the sdbus' library version). The xml2cpp tool would then in turn print out the defined value when passed the --version flag.

**Comment by sangelovic** [comment]
Hey @br337, yes, please open a PR with the solution you proposed (an alternative that comes to my mind would be to pass the version as a preprocessor definition via `target_compile_definitions()`, but I'll leave the final choice up to you). Thank you.
