### ISSUE TITLE
How to get additional information (e.g. info on credentials) of message in method async implement of an adaptor?

### ISSUE THREAD

**Issue by nero-ruijie** [Kistler-Group/sdbus-cpp#464]
**Is your feature request related to a problem? Please describe.**
We need peer UID as a key to exec external scripts which results in:
1. implement the method in async manner on server/adaptor side.
2. a way to get peer UID in the async callback.
well, the message context stored in sdbus::Result<...> is marked as private.

I'm a beginner of dbus and got confused why qdbus/golang-dbus-binding also dropped the message context in high level or convenience abstractions.  Maybe there is some misunderstanding.

**Comment by sangelovic** [comment]
The async D-Bus method implementation callback you register on the server side has the context -- just call `getCurrentlyProcessedMessage()` through the `IObject` interface. A working example in integration tests: https://github.com/Kistler-Group/sdbus-cpp/blob/master/tests/integrationtests/TestAdaptor.cpp#L141

See also documentation here: https://github.com/Kistler-Group/sdbus-cpp/blob/master/docs/using-sdbus-c%2B%2B.md#accessing-a-corresponding-d-bus-message and here: https://github.com/Kistler-Group/sdbus-cpp/blob/master/docs/using-sdbus-c%2B%2B.md#accessing-a-corresponding-d-bus-message-1
