### ISSUE TITLE
Branch naming

### ISSUE THREAD

**Issue by ardazishvili** [Kistler-Group/sdbus-cpp#49]
Proposal: reflect the purpose of the branch in its name(prefix), e.g feature/xxx, bugfix/xxx, etc. Short list of types:
1) feature
2) bugfix
3) refactor
4) documentation
5) testing - add unit/integration/... tests
I can add it to CONTRIBUTING.md (non-existing yet)

**Comment by sangelovic** [comment]
EYes, that would be fine. Just that I would shorten documentation (it's too
long) to doc.

Is there a way to check/enforce that branch naming by GitHub?

There is probably more to add for the project to be more open source
friendly and compliant. Github mentions some best practices for OSS
projects (code of conduct, for instance). I haven't looked into them more
closely yet, though.
