### ISSUE TITLE
Receive array

### ISSUE THREAD

**Issue by rogerdahl** [Kistler-Group/sdbus-cpp#5]
Is it possible to handle a message that contains an array?

I'm trying to read song metadata from Clementine. On the bus, it looks like this:

```
method call time=1519588131.715176 sender=:1.261 -> destination=org.mpris.clementine serial=2 path=/Player; interface=org.freedesktop.MediaPlayer; member=GetMetadata
method return time=1519588131.715434 sender=:1.169 -> destination=:1.261 serial=602 reply_serial=2
   array [
      dict entry(
         string "album"
         variant             string "Rayn Project (Ptrance)"
      )
      ...
```

**Comment by sangelovic** [comment]
Sure, sdbus-c++ handles arrays. The array returned by that GetMetadata method seems to be a D-Bus dictionary, which is represented as a std::map container in sdbus-c++. So the C++ signature would look like `std::map<std::string, sdbus::Variant> getMetadata();`

**Comment by rogerdahl** [comment]
Tried that now, but it doesn't seem to work for me.

I wrote it up like so:

```
std::unique_ptr<sdbus::IObjectProxy> createPlayerProxy()
{
  std::unique_ptr<sdbus::IConnection> c = sdbus::createSessionBusConnection();
  auto playerProxy = sdbus::createObjectProxy(
    *c.release(), CLEMENTINE_SERVICE_NAME, PLAYER_OBJECT_PATH);
  return playerProxy;
}

void getMetadata()
{
  std::map<std::string, sdbus::Variant> r;
  createPlayerProxy()
    ->callMethod("GetMetadata")
    .onInterface(MEDIA_PLAYER_INTERFACE_NAME)
    .storeResultsTo(r);
```

The error is:

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Signal: SIGABRT (Aborted)
```
I based it on a function that receives an `int`, which works:

```
int getPlayerPosition()
{
  int pos;
  createPlayerProxy()
    ->callMethod("PositionGet")
    .onInterface(MEDIA_PLAYER_INTERFACE_NAME)
    .storeResultsTo(pos);
  return pos;
}
```

Here's what I resorted to, calling the C API for `GetMetadata`:

```
string getPlayerCurrentPath()
{
  string path;

  sd_bus_error error = SD_BUS_ERROR_NULL;
  sd_bus_message* reply = NULL;
  sd_bus* bus = NULL;

  // Connect to the Session bus (not System bus)
  checkSdbusCall(sd_bus_open_user(&bus));

  checkSdbusCall(
    sd_bus_call_method(
      bus, "org.mpris.clementine", /* service to contact */
      "/Player", /* object path */
      "org.freedesktop.MediaPlayer", /* interface name */
      "GetMetadata", /* method name */
      &error, /* object to return error in */
      &reply, /* return message on success */
      "" /* input signature */
      ) /* second argument */
    );

  // Parse the response message
  checkSdbusCall(
    sd_bus_message_enter_container(reply, SD_BUS_TYPE_ARRAY, "{sv}"));

  while (sd_bus_message_enter_container(reply, SD_BUS_TYPE_DICT_ENTRY, "sv")
         > 0) {
    const char* key;
    const char* value;
    char type;

    checkSdbusCall(sd_bus_message_read_basic(reply, SD_BUS_TYPE_STRING, &key));
    checkSdbusCall(sd_bus_message_peek_type(reply, &type, &value));

    if (type == SD_BUS_TYPE_VARIANT) {
      checkSdbusCall(
        sd_bus_message_enter_container(reply, SD_BUS_TYPE_VARIANT, value));
      checkSdbusCall(sd_bus_message_peek_type(reply, &type, &value));
      if (type == SD_BUS_TYPE_STRING) {
        checkSdbusCall(sd_bus_message_read_basic(reply, type, &value));
        // std::cout << key << ": " << value << std::endl;
        if (string(key) == "location") {
          path = value;
        }
      }
      else {
        sd_bus_message_skip(reply, NULL);
      }
      checkSdbusCall(sd_bus_message_exit_container(reply));
    }
    checkSdbusCall(sd_bus_message_exit_container(reply));
  }

  sd_bus_error_free(&error);
  sd_bus_message_unref(reply);
  sd_bus_unref(bus);
  replace_all(path, "file://", "");
  return path;
}
```

**Comment by rogerdahl** [comment]
Thank you for the reply, and for spotting the leak. I'm getting the same error though, with:

```
  auto c = sdbus::createSessionBusConnection();
  auto playerProxy = sdbus::createObjectProxy(
    *c, CLEMENTINE_SERVICE_NAME, PLAYER_OBJECT_PATH
  );
  std::map<std::string, sdbus::Variant> r;
  playerProxy
    ->callMethod("GetMetadata")
    .onInterface(MEDIA_PLAYER_INTERFACE_NAME)
    .storeResultsTo(r);
```

**Comment by sangelovic** [comment]
Considering the previous example with `createPlayerProxy()`, I would've guessed that the problem is a result of using already deleted D-Bus connection (the connection got deleted at the end of createPlayerProxy scope, but the proxy object still kept reference to it). The latest code fragment however seems well-formed. Do sdbus-c++ unit tests and integration tests pass fine for you?

**Comment by rogerdahl** [comment]
The tests didn't compile for me, and I didn't investigate. I had to build latest version of gcc from source in order to get support for `uncaught_exceptions`, which may be related.

Would you be interested in testing it against the Clementine player yourself? If so, I'll supply a complete minimal example.

**Comment by lukasdurfina** [comment]
Yes please, supply the example.
For `uncaught_exceptions`, you need compiler with c++17 support. I am sure you can use some packaged version without compiling it by yourself.

**Comment by rogerdahl** [comment]
Here goes:

```
#include <sdbus-c++/sdbus-c++.h>

const char* CLEMENTINE_SERVICE_NAME = "org.mpris.clementine";
const char* PLAYER_OBJECT_PATH = "/Player";
const char* MEDIA_PLAYER_INTERFACE_NAME = "org.freedesktop.MediaPlayer";

int main(int argc, char** argv)
{
  auto c = sdbus::createSessionBusConnection();
  auto playerProxy = sdbus::createObjectProxy(
    *c, CLEMENTINE_SERVICE_NAME, PLAYER_OBJECT_PATH
  );
  std::map<std::string, sdbus::Variant> r;
  playerProxy
    ->callMethod("GetMetadata")
    .onInterface(MEDIA_PLAYER_INTERFACE_NAME)
    .storeResultsTo(r);
  return 0;
}
```
I get:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
```

**Comment by sangelovic** [comment]
Can you please be more specific about the compilation issues of sdbus-c++ tests?

**Comment by rogerdahl** [comment]
I'm on Mint 18.3, which is based on Ubuntu 16.04. The tests failed to compile with:

```
unittests/libsdbus-c++_unittests.cpp:26:25: fatal error: gmock/gmock.h: No such file or directory
```

I made an attempt at making googletest available in my local gcc 7.3 environment, but ran into problems and figured it wasn't worth resolving them to get the tests to run. If you're unable to reproduce the issue based on the minimal example, I'll go ahead and figure out the googletest stuff so that I can run the tests.

**Comment by lukasdurfina** [comment]
Hi Roger, sorry for a late response.
I tried your example on the new testing Ubuntu (18.04).
Unfortunately, the clementine has only new mpris2 interface, so I have to update it lightly. Anyway, attached example works without any issue. Can you install gmock on your system and run unit and integration tests?
```
#include <sdbus-c++/sdbus-c++.h>
#include <iostream>

const char* CLEMENTINE_SERVICE_NAME = "org.mpris.MediaPlayer2.clementine";
const char* PLAYER_OBJECT_PATH = "/org/mpris/MediaPlayer2";
const char* MEDIA_PLAYER_INTERFACE_NAME = "org.mpris.MediaPlayer2.Player";

int main(int argc, char** argv)
{
    auto c = sdbus::createSessionBusConnection();
    auto playerProxy = sdbus::createObjectProxy(*c, CLEMENTINE_SERVICE_NAME, PLAYER_OBJECT_PATH);
    std::map<std::string, sdbus::Variant> r = playerProxy
        ->getProperty("Metadata")
        .onInterface(MEDIA_PLAYER_INTERFACE_NAME);
    for (const auto& p : r)
    {
        std::cout << "Key: " << p.first << std::endl;
    }
    return 0;
}
```

**Comment by rogerdahl** [comment]
Sorry for the delay, Lukas. Getting this working on 16.04 is no longer a priority for me, as I plan on moving on to 18.04 shortly, and your modified example demonstrates that it works there. Feel free to close this, or, if you leave it open, I'll do a final update after moving my code to 18.04.

**Comment by danderson-presonus** [comment]
> There is signature `{sv}`, what stands for `std::map<std::string, sdbus::Variant>`, so the call looks ok.
> The issue might be in the way how you manage pointers. The code `*c.release()` is bad, because at least it causes a memory leak.

Is this mapping of dbus signatures to sdbus-c++ data structures documented somewhere?  This reply solved my problem for me but not before reading through what documentation I could find and not finding the answer...

**Comment by sangelovic** [comment]
@danderson-presonus I've created issue #204 for that. The documentation is there, but in the tests, e.g. here: https://github.com/Kistler-Group/sdbus-cpp/blob/master/tests/unittests/TypeTraits_test.cpp, or in the production code, here: https://github.com/Kistler-Group/sdbus-cpp/blob/master/include/sdbus-c%2B%2B/TypeTraits.h. Nevertheless, we will add it to the official docs.

**Comment by danderson-presonus** [comment]
Thanks!
