### ISSUE TITLE
BUILD_LIBSYSTEMD not effect

### ISSUE THREAD

**Issue by lujfsd** [Kistler-Group/sdbus-cpp#56]
Hi, i got some trouble at v0.6.0

This is my config :
 ` cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CODE_GEN=ON -DBUILD_LIBSYSTEMD=ON -DBUILD_DOC=OFF `

But:
CMake checking libsystemd.
  **-- Checking for module 'libsystemd>=236' 
    --   Requested 'libsystemd >= 236' but version of systemd is 229
   You may find new versions of systemd at http://www.freedesktop.org/wiki/Software/systemd
  CMake Error at /usr/share/cmake-3.14/Modules/FindPkgConfig.cmake:457 (message):
    A required package was not found
    Call Stack (most recent call first):
  /usr/share/cmake-3.14/Modules/FindPkgConfig.cmake:642 (_pkg_check_modules_internal)
  CMakeLists.txt:16 (pkg_check_modules)
-- Configuring incomplete, errors occurred!
See also "/home/conn/build_imx6/sdbus-cpp/build/CMakeFiles/CMakeOutput.log".**

**Comment by sangelovic** [comment]
Hi, v0.6.0 does not support the feature of building libsystemd as part of building sdbus-c++. It's one of the most recent features that will be released in a few days (probably as v0.7.0). Until then, you can check out master branch directly and work with that.

**Comment by lujfsd** [comment]
Yes,it works.Thanks
