### ISSUE TITLE
Add support for the UNIX_FD type

### ISSUE THREAD

**Issue by mdavis777** [Kistler-Group/sdbus-cpp#59]
Currently there is no support for the UNIX_FD "h" type.

From the spec 

UNIX_FD | 32-bit unsigned integer in the message's byte order. The actual file descriptors need to be transferred out-of-band via some platform specific mechanism. On the wire, values of this type store the index to the file descriptor in the array of file descriptors that accompany the message.

**Comment by mdavis777** [comment]
I see there is already a [pull reques](https://github.com/Kistler-Group/sdbus-cpp/pull/22)t to fix it.
I will let you decide if you want to leave the Issue open for tracking or just close it.

**Comment by sangelovic** [comment]
Hi, thanks for commenting, yes this is just being worked upon. I'll leave this open and close it with PR merge.

**Comment by sangelovic** [comment]
Fixed by #61
