### ISSUE TITLE
How to get object path?

### ISSUE THREAD

**Issue by DSiekmeier** [Kistler-Group/sdbus-cpp#65]
Good morning,

My project is based on the auto-generated files using sdbus-c++-xml2cpp. I have the following use case when trying to bring a modem into operation, using the oFono-API:

the "Manager" class reads all available modems with the method _GetModems()_ from org.ofono.Manager. This method returns among other properties, the objectPath to the modem, e.g. _/phonesim_. For each Modem a instance of the "Modem" class will be instantiated.

Each Modem instance should know its objectPath, because there are the later needed interfaces, like _org.ofono.SimManager_. So my idea was to call the constructor of "Modem" (inside the Manager class) like this:

> this->modems.push_back(new Modem(destination, objectPath, pin, apn));

Whereas objectPath could be the before mentioned _/phonesim_.

Inside the constructor of "Modem" I have no chance to store the objectPath because of the inherited _ProxyInterfaces(std::move(destination), std::move(objectPath))_.

So as a workaround I changed the constructor of "Modem" to get an additional parameter "modemObjectPath", which is in fact the same as _objectPath_.

I am looking forward for some ideas or maybe concepts from the community I missed in this particular case.

Kind Regards

**Comment by sangelovic** [comment]
Good afternoon,

You don't have to `std::move` the passed-in argument into the base class constructor. Base class (i.e. `ProxyInterfaces`) [constructor takes parameters by values](https://github.com/Kistler-Group/sdbus-cpp/blob/master/include/sdbus-c%2B%2B/ProxyInterfaces.h#L106), which provides you freedom of choosing on per-argument basis whether you want to copy or move arguments into `ProxyInterfaces` constructor.

That said, in your `Modem` proxy class, you can simply do something like:

```c++
class ModemProxy : public sdbus::ProxyInterfaces<org::ofono::SimManager_proxy/*, ...*/>
{
public:
    ModemProxy(std::string destination, const std::string& objectPath /*, pin, apn parameters*/)
        : ProxyInterfaces(std::move(destination), objectPath)
        , myCopyOfObjectPath(objectPath)
    {
        registerProxy();
    }

    /*...*/

private:
    std::string myCopyOfObjectPath;
};
```

Did this answer your question?

**Comment by DSiekmeier** [comment]
Hi Stanislav,
you are completely right, I missed that point. So this solves my problem, thank you very much.

Kind Regards.
