### ISSUE TITLE
Error when communicating with UDisk2 Raid

### ISSUE THREAD

**Issue by mdavis777** [Kistler-Group/sdbus-cpp#68]
I am using sdbus-c++ to interface with UDisk2 and encountered an interesting problem.  I don't know if you can really do anything about it, but I thought it was best to mention it anyways.

If you use a method call to stop a raid:
`mRaidProxy>callMethodAsync("Stop").onInterface("org.freedesktop.UDisks2.MDRaid").withArguments(std::map<std::string, sdbus::Variant>());`
This causes the following error:
`'sdbus::Error'
  what():  [org.freedesktop.DBus.Error.UnknownMethod] No such interface “org.freedesktop.UDisks2.MDRaid” on object at path /org/freedesktop/UDisks2/mdraid/082bd1b0_830621df_84f8c775_5b2a1938
`
The command actually goes through and works fine.  The best I can tell it is because that action will close the remote object /org/freedesktop/UDisks2/mdraid/082bd1b0_830621df_84f8c775_5b2a1938 which is what the proxy is connected to.  

Doing it as an async returns fine without any issue.

**Comment by sangelovic** [comment]
This looks like the error reply is returned by either dbus-daemon or the service itself. Calling it asynchronously means no reply is expected and waited for, so I suspect the error is still raised but simply not received by the client. As for the cause, have you tried making the same call using pure C sd-bus API? Or via some other D-Bus binding (e.g. Qt D-Bus, libdbus-c++, ..)? This seems to be rather a more general D-Bus problem...

**Comment by mdavis777** [comment]
I have tried with normal command line interfaces like gdbus.  It didn't have an error, but that doesn't mean it didn't suppress it either.  

I will give it a try with another API and let you know if it has similar errors.

**Comment by sangelovic** [comment]
Any news? Can we close this issue?

**Comment by mdavis777** [comment]
I haven't had any time to really check it and I don't know when I will get some.  I will just close it and if I ever get back to it with more data that proves its an issue I will reopen.
