### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by klukaspl** [Kistler-Group/sdbus-cpp#7]
Hi, 

when compiling I reached the following issue:

Message.cpp: In member function ‘void sdbus::Message::seal()’:
Message.cpp:553:83: error: ‘sd_bus_message_seal’ was not declared in this scope
     auto r = sd_bus_message_seal((sd_bus_message*)msg_, messageCookie, sealTimeout);
                                                                                   ^
Message.cpp: In function ‘sdbus::Message sdbus::createPlainMessage()’:
Message.cpp:669:72: error: ‘sd_bus_message_new’ was not declared in this scope
     r = sd_bus_message_new(bus, &sdbusMsg, _SD_BUS_MESSAGE_TYPE_INVALID);

Could you please give me a hint how to avoid those errors?

BR,

Krzysztof

**Comment by lukasdurfina** [comment]
Hi Krzysztof,

your systemd library is older than is needed.
You need to have at least v236: https://github.com/systemd/systemd/blob/v236/src/systemd/sd-bus.h#L232

BR,
Lukas

**Comment by klukaspl** [comment]
Hi Lukas,

Thanks a lot! Indeed I am using Kubuntu 16.04 with libsystemd-dev v229, and there is no newer for it from official packages. I am a bit afraid to upgrade manually to not break something in my OS.

Thanks
Krzysztof

**Comment by lukasdurfina** [comment]
You are welcome. 18.04 LTS will be published very soon and it will have the version you need.
