### ISSUE TITLE
 SdbusTestObject.AnswersMachineUuidViaPeerInterface throws

### ISSUE THREAD

**Issue by riuriuriu** [Kistler-Group/sdbus-cpp#75]
The ` SdbusTestObject.AnswersMachineUuidViaPeerInterface` is expected not to throw, but on our "Beaglebone-like" board it does throw:

> [ RUN      ] SdbusTestObject.AnswersMachineUuidViaPeerInterface
terminate called after throwing an instance of 'sdbus::Error'
  what():  [org.freedesktop.DBus.Error.FileNotFound] Failed to process bus requests (No such file or directory)

Note that there was #74 created for the terminate caused by the exception. This Issue is about the exception happening at all.

Is there a new pre-condition for the integration-tests? Some files missing?

**Comment by sangelovic** [comment]
Hi Urs, I guess you are right -- probably a file is missing (or rather searched for in a wrong location). Could you please check and let me know whether '/var/lib/dbus/machine-id' file and '/etc/machine-id' file are present in your file system? I suspect the former is present and contains valid machine UUID whereas the latter isn't there (and if you have a non-systemd environment, it rightfully should not be there).

**Comment by riuriuriu** [comment]
Hi Stano
Yes, it's as you suspected. The `/var/lib/dbus/machine-id` is present and contains a UUID, whereas `/etc/machine-id` is missing.

**Comment by sangelovic** [comment]
Ok, so there is another systemd-ism in implementation of GetMachineId by libsystemd. It checks for one file only, ignores the other. I think it should look into /etc/machine-id first, if that is not present then into the other one, if that is not present then return an error reply, not fail hard as we discussed in #74.

I will ask at systemd forum about that.

**Comment by sangelovic** [comment]
So I got response from systemd developers, see https://lists.freedesktop.org/archives/systemd-devel/2019-September/043497.html. The solution they present is making a symlink `/etc/machine-id` pointing to `/var/lib/dbus/machine-id`. Or using (newer) dbus that is said to support `/etc/machine-id`. Is this an acceptable solution for you? Another approach would be to disable GetMachineId test case in your environment.

**Comment by riuriuriu** [comment]
> Is this an acceptable solution for you?

Yes. I thought it's more a workaround, but when the D-Bus spec says that the machine-id is not optional, then that's probably the only right solution.

Thank you for clarification.
