### ISSUE TITLE
Interacting with systemd services programmatically in c++

### ISSUE THREAD

**Issue by ringlej** [Kistler-Group/sdbus-cpp#79]
I'm looking for a way from my c++ project to be able to do from code things that a user can do with `systemctl`
For example: `systemctl restart some.service`
Before I invest time in learning about sdbus-cpp, I just want to know if that something that can be done with this library.

TIA,
-Jon

**Comment by sangelovic** [comment]
AFAIK, `systemctl` transforms these command line actions into D-Bus calls to the `org.freedesktop.systemd1` service, which exports `/org/freedesktop/systemd1` object with a number of D-Bus methods, properties and signals. You are probably asking whether you can create a proxy to that systemd1 object by using sdbus-c++ in your application. From what I have seen, I think it should be perfectly possible. Probably the best way is to use D-Bus introspection to introspect [`systemd1` object interface definition](https://github.com/systemd/systemd/blob/master/src/core/dbus-manager.c#L2380), the result of which will be an XML interface description. Then out of this description, you can use `sdbus-c++-xml2cpp` generator to generate adaptor (you don't need that) and proxy classes. Then simply instantiate a proxy (see using-c++ tutorial for how to do that, or look at sdbus-c++ integration/performance/stress tests) and you can issue calls against `systemd1` and receives signals from it.

**Comment by ringlej** [comment]
Thank you. That worked perfectly!
