### ISSUE TITLE
Signal receiver event loop 

### ISSUE THREAD

**Issue by vsemyonoff** [Kistler-Group/sdbus-cpp#82]
Hello,

My question is: how to organize main client's loop properly without any `sleep` calls. Is there any method like poll for signal or wait for event? Wold be nice to clarify that moment in library's manual.

Thank you for the great library, great job!

**Comment by sangelovic** [comment]
Hi,

Thanks for kind words.

How you can organize your main loop depends on what you need. You mentioned
client event loop. So I assume you only have D-Bus proxies there. If you
have a simple client and don't want to distract yourself by connection
details, simply create a proxy that takes no connection parameter.

More on how to approach connections and event loops in both services and
client apps is quite comprehensively described here:
https://github.com/Kistler-Group/sdbus-cpp/blob/master/docs/using-sdbus-c++.md#working-with-d-bus-connections-in-sdbus-c

Is there anything that you'd suggest to clarify more?

**Comment by vsemyonoff** [comment]
Thank you very much, I've made system `D-Bus` connection and called `enterProcessLoop`:
