### ISSUE TITLE
The library cannot find the headers for libsystemd

### ISSUE THREAD

**Issue by dj0405** [Kistler-Group/sdbus-cpp#86]
I have installed libsystemd-dev on Ubuntu 18.04. Running the command `pkg-config --cflags --libs libsystemd` returns `-lsystemd`. So I am sure I have libsystemd-dev installed correctly.

```
systemctl --version
systemd 237

```
**Output of cmake:**

```
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for modules 'GLOBAL;libsystemd>=236'
--   No package 'GLOBAL' found
CMake Error at CMakeLists.txt:21 (message):
  libsystemd of version at least 236 is required, but was not found (you may
  turn BUILD_LIBSYSTEMD on for sdbus-c++ to try downloading and building
  libsystemd in as part of sdbus-c++ during configuration)
```

Any idea what I am missing here? Thank you in advance.

**Comment by lukasdurfina** [comment]
Hi,
this is bad: --   No package 'GLOBAL' found
What version of CMake do you use?
According to the doc https://cmake.org/cmake/help/v3.13/module/FindPkgConfig.html
it seems that at least `3.13` should be use. If so, CmakeLists.txt must be fixed.

**Comment by sangelovic** [comment]
The GLOBAL keyword is indeed supported by CMake >= 3.13. Library's CMakeLists requires at CMake at least 3.12, which however does not yet support GLOBAL keyword. It's a mistake on library's part. You probably have CMake of exactly v3.12. You can solve the issue by upgrading to newer CMake version.
