### ISSUE TITLE
Proxy::sdbus_signal_handler() is returning wrong value.

### ISSUE THREAD

**Issue by olta** [Kistler-Group/sdbus-cpp#93]
Proxy::sdbus_signal_handler() returns 1 (indicating that no more handlers should be invoked), but I believe it should return 0 instead (causing all other handlers to be invoked).

As the code is currently, listening to a signal works for a single proxy, but when there are multiple proxies listening to the same signal, only one of them will actually be triggered.

```
diff --git a/src/Proxy.cpp b/src/Proxy.cpp
index 4873544..f833e01 100644
--- a/src/Proxy.cpp
+++ b/src/Proxy.cpp
@@ -264,7 +264,7 @@ int Proxy::sdbus_signal_handler(sd_bus_message *sdbusMessage, void *userData, sd

callback(message);

-    return 1;
+    return 0;
}

}
```

**Comment by sangelovic** [comment]
Hello, how can I reproduce the scenario you are describing? I created a quick test case for that in my integration tests, but the signal gets delivered to all proxies.

**Comment by olta** [comment]
Hello - I think you need to create two proxies sharing a connection in order to reproduce the issue. I have tried to add a corresponding integration test, but that didn't trigger the problem as each TestingProxy uses its own connection.
Does that help in any way?

**Comment by olta** [comment]
I've managed to come up with a test triggering the problem:
```
commit 8da7bdeac35d3469ac80fd5c47fead0ad3f921fa (HEAD -> dev)
Author: Oliver Tappe <zooey@hirschkaefer.de>
Date:   Wed Mar 25 10:08:36 2020 +0100

    Add test for emitting a signal to multiple proxies on same connection.

diff --git a/tests/integrationtests/AdaptorAndProxy_test.cpp b/tests/integrationtests/AdaptorAndProxy_test.cpp
index 096d90f..7a5df37 100644
--- a/tests/integrationtests/AdaptorAndProxy_test.cpp
+++ b/tests/integrationtests/AdaptorAndProxy_test.cpp
@@ -473,6 +473,18 @@ TEST_F(SdbusTestObject, EmitsSimpleSignalSuccesfully)
     ASSERT_TRUE(waitUntil(m_proxy->m_gotSimpleSignal));
 }
 
+TEST_F(SdbusTestObject, EmitsSimpleSignalToMultipleProxiesSuccesfully)
+{
+    auto proxy1 = std::make_unique<TestingProxy>(*s_connection, INTERFACE_NAME, OBJECT_PATH);
+    auto proxy2 = std::make_unique<TestingProxy>(*s_connection, INTERFACE_NAME, OBJECT_PATH);
+
+    m_adaptor->emitSimpleSignal();
+
+    ASSERT_TRUE(waitUntil(m_proxy->m_gotSimpleSignal));
+    ASSERT_TRUE(waitUntil(proxy1->m_gotSimpleSignal));
+    ASSERT_TRUE(waitUntil(proxy2->m_gotSimpleSignal));
+}
+
 TEST_F(SdbusTestObject, EmitsSignalWithMapSuccesfully)
 {
     m_adaptor->emitSignalWithMap({{0, "zero"}, {1, "one"}});
diff --git a/tests/integrationtests/TestingProxy.h b/tests/integrationtests/TestingProxy.h
index 027af00..c4ea3e0 100644
--- a/tests/integrationtests/TestingProxy.h
+++ b/tests/integrationtests/TestingProxy.h
@@ -43,6 +43,12 @@ public:
         registerProxy();
     }
 
+    TestingProxy(sdbus::IConnection& connection, std::string destination, std::string objectPath)
+        : ProxyInterfaces(connection, std::move(destination), std::move(objectPath))
+    {
+        registerProxy();
+    }
+
     ~TestingProxy()
     {
         unregisterProxy();
l```

**Comment by sangelovic** [comment]
I just came up with the same test case myself, having realized I first had proxies where each had its own connection :) Cool.

So you are right, the signal callback return value prohibits sd-bus from invoking other callbacks. I was not aware of that subtle difference.

Do you want to create a pull request with the changes you've proposed (including the new test case and additional TestingProxy constructor)?

**Comment by olta** [comment]
Done.
